import test from 'node:test';
import assert from 'node:assert/strict';
import {authFailure,authRedirectFailure,emailLinkFailure,retrySeconds,withAuthTimeout} from '../src/ai-auth-feedback.js';
test('rate-limit feedback never claims another email was sent',()=>{for(const e of [{status:429},{message:'email rate limit exceeded'}]){assert.match(authFailure(e),/No new email was sent/);assert.match(authFailure(e),/most recent link/);}});
test('slow monitoring connection gives a retryable message without losing results',()=>{assert.match(authFailure({name:'TimeoutError',message:'The operation was aborted due to timeout'}),/saved results are still there/);});
test('resend cooldown expires using elapsed wall time',()=>{assert.equal(retrySeconds(61000,1000),60);assert.equal(retrySeconds(61000,60500),1);assert.equal(retrySeconds(61000,62000),0);});
test('gateway failures do not say the account or email link is invalid',()=>{assert.match(authFailure({status:504,message:'HTTP 504'}),/temporarily unavailable/);assert.match(emailLinkFailure({status:504}),/Check your inbox/);});
test('global email limits direct users to an email-free sign-in method',()=>{assert.match(emailLinkFailure({status:429,code:'over_email_send_rate_limit'}),/Google sign-in/);});
test('expired callback links are explained without echoing URL data',()=>{assert.match(authRedirectFailure('#error=access_denied&error_code=otp_expired'),/expired or was already used/);assert.equal(authRedirectFailure('#'), '');});
test('provider callback failures are not blamed on the user',()=>{assert.match(authRedirectFailure('#error=server_error&error_code=unexpected_failure&error_description=internal'),/provider is temporarily unavailable/);});
test('failed OAuth code exchange is presented as a provider problem',()=>{assert.match(authRedirectFailure('#error=access_denied&error_description=Unable+to+exchange+external+code'),/provider is temporarily unavailable/);});
test('slow email requests stop the sending state',async()=>{await assert.rejects(withAuthTimeout(new Promise(()=>{}),5),{name:'TimeoutError'});});
