import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {Readable} from 'node:stream';
import {localCollectorStore} from '../server/collector-store.mjs';import {validateSchedule,enqueueDue} from '../server/collection-schedule.mjs';import {crawlCoverage,verifyCoverage} from '../server/page-coverage.mjs';import {searchapiHandler} from '../server/searchapi-handler.mjs';
const business={name:'Brand',domain:'brand.example'},question={text:'Which tool?',topic:'Tools',type:'Unbranded'};
async function call(handler,body,worker=false){const req=Readable.from([JSON.stringify(body)]);req.method='POST';req.headers={origin:'http://127.0.0.1:5174',host:'127.0.0.1:5174','content-type':'application/json'};req.internalWorker=worker;const res={setHeader(){},end(raw){this.body=JSON.parse(raw);}};await handler(req,res);return res;}
test('cross-process stores serialize mutations and retain the budget ledger',async()=>{const directory=await mkdtemp(join(tmpdir(),'d2-store-'));try{const a=localCollectorStore(directory),b=localCollectorStore(directory);const token=await a.acquire();assert.ok(token);assert.equal(await b.acquire(),null);await a.save({attempts:4,analysisAttempts:12,answers:[]});await b.release('wrong');assert.equal(await b.acquire(),null);await a.release(token);const next=await b.acquire();assert.ok(next);assert.equal((await b.load()).analysisAttempts,12);await b.release(next);}finally{await rm(directory,{recursive:true});}});
test('scheduler deduplicates daily jobs and records ambiguous interruption without retry',()=>{const now=new Date('2026-01-02T00:00:00Z');const schedule=validateSchedule({enabled:true,engines:['chatgpt','gemini'],cadence:'daily',questions:[question]},business,new Date('2026-01-01'));const state={schedules:{[business.domain]:schedule}};enqueueDue(state,now);enqueueDue(state,now);assert.equal(state.jobs.length,2);state.jobs[0].status='running';state.jobs[0].startedAt='2026-01-01';enqueueDue(state,now);assert.equal(state.jobs[0].status,'failed');assert.throws(()=>validateSchedule({...schedule,questions:[question,question]},business));});
test('coverage stays same-origin, bounded, and requires verbatim supporting evidence',async()=>{let calls=[];const crawl=await crawlCoverage('https://brand.example',{limit:2,fetchPage:async url=>{calls.push(url);return {url,html:'<title>Tool</title><main>Our editor includes a visual CMS for teams.</main><a href="/features">Features</a><a href="https://elsewhere.example">Other</a>'};}});assert.equal(calls.length,2);assert.equal(crawl.pages.length,2);const good=verifyCoverage({results:[{prompt:question.text,status:'Covered',page:0,evidence:'includes a visual CMS for teams.',reason:'CMS available'}]},[question],crawl)[0];assert.equal(good.status,'Covered');const bad=verifyCoverage({results:[{prompt:question.text,status:'Covered',page:0,evidence:'Invented text that is not on this page',reason:''}]},[question],crawl)[0];assert.equal(bad.status,'Unassessed');});
test('library revision conflicts preserve existing data and pausing cancels queued jobs',async()=>{const directory=await mkdtemp(join(tmpdir(),'d2-library-'));try{const store=localCollectorStore(directory),h=searchapiHandler({local:true,store});const row={...question,id:'q',status:'saved',tracking:true};let r=await call(h,{action:'library',business,rows:[row],revision:0});assert.equal(r.body.library.revision,1);assert.equal((await call(h,{action:'library',business,rows:[],revision:0})).statusCode,409);await call(h,{action:'schedule',business,schedule:{enabled:true,cadence:'daily',engines:['chatgpt'],questions:[question]}});await call(h,{action:'library',business,rows:[{...row,tracking:false}],revision:1});assert.equal((await store.load()).schedules[business.domain].enabled,false);}finally{await rm(directory,{recursive:true});}});
test('worker failures pause scheduling and cannot be triggered by public request bodies',async()=>{const directory=await mkdtemp(join(tmpdir(),'d2-worker-'));try{const store=localCollectorStore(directory);const schedule={...validateSchedule({enabled:true,cadence:'daily',engines:['gemini'],questions:[question]},business),nextAt:'2000-01-01'};await store.save({attempts:0,answers:[],schedules:{[business.domain]:schedule}});const h=searchapiHandler({local:true,store,key:'test',analysisKey:'test',request:async url=>url.includes('/me')?{ok:true,json:async()=>({account:{remaining_credits:9,monthly_allowance:0}})}:{ok:false,status:503}});assert.equal((await call(h,{action:'scheduleTick',business})).statusCode,403);const r=await call(h,{action:'scheduleTick',business},true);assert.equal(r.statusCode,502);const state=await store.load();assert.equal(state.jobs[0].status,'failed');assert.equal(state.schedules[business.domain].enabled,false);assert.equal(state.attempts,1);await call(h,{action:'scheduleTick',business},true);assert.equal((await store.load()).attempts,1);}finally{await rm(directory,{recursive:true});}});

test('cloud ownership validates the session and denies another account',async()=>{
 const {verifiedOwner}=await import('../server/cloud-runtime.mjs');
 const client={auth:{getUser:async token=>({data:{user:token==='valid'?{id:'owner'}:{id:'other'}}})},from:()=>({select:()=>({eq:()=>({single:async()=>({data:{owner_id:'owner'}})})})})};
 assert.equal((await verifiedOwner({headers:{authorization:'Bearer valid'}},client)).id,'owner');
 await assert.rejects(()=>verifiedOwner({headers:{}},client),/Sign in/);
 await assert.rejects(()=>verifiedOwner({headers:{authorization:'Bearer wrong'}},client),/not the Dashboard 2/);
});
