import React,{useState,useEffect,useRef} from 'react';
import {aiCloud,aiFetch,syncBusinessProfiles,loadCloudBusinesses} from './ai-cloud';
import {BUSINESS_KEY,businessStorageKey,validBusiness} from './ai-business';
import {AUTH_RETRY_KEY,authFailure,authRedirectFailure,emailLinkFailure,emailSendLimited,retrySeconds,withAuthTimeout} from './ai-auth-feedback';
import {GoogleIdentityButton} from './GoogleIdentityButton';
import './ai-auth.css';
export function AiCloudAccount({entry=false,onConnected}){
 const [user,setUser]=useState(null),[checking,setChecking]=useState(true),[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(()=>authRedirectFailure(location.hash));
 const [retryAt,setRetryAt]=useState(()=>{try{return Number(localStorage.getItem(AUTH_RETRY_KEY)||0);}catch{return 0;}}),[now,setNow]=useState(Date.now());
 const connecting=useRef(false),connectedUser=useRef(null),callback=useRef(onConnected);callback.current=onConnected;
 const seconds=retrySeconds(retryAt,now);
 useEffect(()=>{if(!seconds)return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[retryAt,seconds>0]);
 useEffect(()=>{const update=e=>{if(e.key===AUTH_RETRY_KEY){setRetryAt(Number(e.newValue||0));setNow(Date.now());}};window.addEventListener('storage',update);if(authRedirectFailure(location.hash))history.replaceState(history.state,'',location.pathname+location.search);return()=>window.removeEventListener('storage',update);},[]);
 useEffect(()=>{if(!aiCloud){setChecking(false);return;}let live=true,authChanged=false;withAuthTimeout(aiCloud.auth.getSession()).then(({data,error})=>{if(live){if(!authChanged)setUser(data.session?.user||null);setChecking(false);if(error&&!authChanged)setError(authFailure(error));}}).catch(e=>{if(live&&!authChanged){setChecking(false);setError(authFailure(e));}});const {data}=aiCloud.auth.onAuthStateChange((event,session)=>{if(live){if(event!=='INITIAL_SESSION')authChanged=true;setUser(session?.user||null);setChecking(false);if(session?.user)setError('');}});return()=>{live=false;data.subscription.unsubscribe();};},[]);
 function cooldown(milliseconds=60000){const until=Date.now()+milliseconds;setRetryAt(until);setNow(Date.now());try{localStorage.setItem(AUTH_RETRY_KEY,String(until));}catch{}}
 async function signInGoogle(token,nonce){if(busy)return;setBusy(true);setError('');setMessage('');try{const {error}=await withAuthTimeout(aiCloud.auth.signInWithIdToken({provider:'google',token,nonce}));if(error)throw error;localStorage.setItem('d2-ai-return','1');}catch(e){setError(authFailure(e));}finally{setBusy(false);}}
 async function signIn(e){e.preventDefault();if(busy||seconds)return;setBusy(true);setError('');setMessage('');try{const {error}=await withAuthTimeout(aiCloud.auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:location.origin+'/'}}));if(error)throw error;try{localStorage.setItem('d2-ai-return','1');}catch{}cooldown();setMessage('Sign-in link sent. Open the latest email to continue to AI Visibility.');}catch(e){if(emailSendLimited(e))cooldown(60*60*1000);else if(e.status>=500||e.name==='TimeoutError')cooldown();setError(emailLinkFailure(e));}finally{setBusy(false);}}
 async function connect(){if(connecting.current)return;connecting.current=true;setBusy(true);setError('');setMessage('');try{
  const response=await aiFetch('/api/ai/connections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'claim'}),signal:AbortSignal.timeout(65000)});const result=await response.json().catch(()=>({}));if(!response.ok){const failure=Error(result.error||'Monitoring connection is temporarily unavailable. Please retry.');failure.status=response.status;throw failure;}
  const key=businessStorageKey(user.id);
  let local;try{local=JSON.parse(localStorage.getItem(key)||'null');}catch{local=null;}
  if(!local&&result.legacyOwner){try{local=JSON.parse(localStorage.getItem(BUSINESS_KEY)||'null');}catch{local=null;}}
  if(!local||typeof local!=='object')local={active:'',profiles:{}};
  local.profiles=Object.fromEntries(Object.entries(local.profiles||{}).filter(([,profile])=>validBusiness(profile)));
  try{await syncBusinessProfiles(local.profiles);const cloud=await loadCloudBusinesses();for(const row of cloud)local.profiles[row.domain]=row.profile;if(!local.profiles[local.active])local.active=cloud[0]?.domain||'';}catch{/* Local profiles remain available while cloud reads recover. */}
  localStorage.setItem(key,JSON.stringify(local));localStorage.removeItem('d2-ai-return');connectedUser.current=user.id;setMessage('Your private monitoring workspace is connected.');callback.current?.(user);
 }catch(e){if(/session expired|sign in again/i.test(e.message||'')){await aiCloud.auth.signOut({scope:'local'});setUser(null);setEmail('');setError('Your session expired. Choose a sign-in method again.');}else if(e.status===503||e.name==='TimeoutError')setError('You are signed in, but monitoring storage is taking too long. Try “Continue to AI Visibility” again; your account and saved results are safe.');else setError(authFailure(e));}finally{setBusy(false);connecting.current=false;}}
 useEffect(()=>{if(entry&&user&&connectedUser.current!==user.id){connectedUser.current=user.id;callback.current?.(user);}},[entry,user?.id]);
 return <section className={entry?'aiv-auth-form':'panel aiv-cloud-account'}><h3>{entry?'Sign in to AI Visibility':'Cloud account'}</h3><p>{entry?'Keep your businesses, prompts, and results together. Sign in once, then add your website.':'Manage the account connected to your AI visibility history.'}</p>{checking?<p role="status">Checking your session…</p>:!aiCloud?<p role="alert">Sign-in is temporarily unavailable. Please try again later.</p>:user?<><p>Signed in as {user.email}</p><div className="pr-top-actions"><button className="cs-button filled" disabled={busy} onClick={entry?()=>callback.current?.(user):connect}>{busy?'Connecting…':entry?'Continue to AI Visibility':'Connect monitoring account'}</button><button className="cs-button" disabled={busy} onClick={async()=>{setMessage('');setError('');setBusy(true);const {error}=await aiCloud.auth.signOut({scope:'local'});setBusy(false);if(error)setError(authFailure(error));else{connectedUser.current=null;setUser(null);setEmail('');}}}>Use another account</button></div></>:<><GoogleIdentityButton disabled={busy} onCredential={signInGoogle} onError={e=>setError(authFailure(e))}/><div className="aiv-auth-divider"><span>or use email</span></div><form onSubmit={signIn}><label>Email address<input type="email" required autoComplete="email" placeholder="you@company.com" value={email} disabled={busy} onChange={e=>{setEmail(e.target.value);setMessage('');setError('');}}/></label><button className="cs-button filled" disabled={busy||seconds>0}>{busy?'Please wait…':seconds>60?'Email temporarily unavailable':seconds>0?`Try again in ${seconds}s`:'Send sign-in link'}</button><small>Email links are single-use. Open the newest link only once.</small></form></>}{error?<p className="aiv-auth-error" role="alert">{error}</p>:message?<p className="aiv-auth-message" role="status">{message}</p>:null}</section>;
}
