import React,{useState,useEffect} from 'react';
import {AiCloudAccount} from './AiCloudAccount';
import {aiFetch} from './ai-cloud';
import { ArrowUpRight, Check, Clock3 } from 'lucide-react';
export function AiConnections() {
 const [status,setStatus]=useState(null);useEffect(()=>{aiFetch('/api/ai/connections',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"action":"status"}'}).then(r=>r.json()).then(setStatus).catch(()=>setStatus({error:true}));},[]);
 const services=[
 {name:'Website reader',status:'Connected',ready:true,purpose:'Reads public website pages for business context and prompt coverage.',detail:'Coverage scans inspect up to 12 linked public HTML pages and retain supporting excerpts. Unread or JavaScript-only content is not assumed covered.'},
 {name:'Supabase',status:status?.cloudReachable?'Connected':status?'Unavailable':'Checking…',ready:status?.cloudReachable,purpose:'Private monitoring history, prompt library, job queue and one shared budget ledger.',detail:'Sign in with your email to open your own monitoring workspace on this device or the deployed dashboard.'},
 {name:'AI answer collection',status:status?.searchConfigured?'Connected':'Not configured',ready:status?.searchConfigured,purpose:'Collects ChatGPT and Gemini answers through SearchAPI.',detail:'Uses remaining free-trial credits only. The retired Perplexity endpoint is excluded. Engine availability is checked by each request; failures pause schedules instead of inventing observations or retrying charges.'},
 ...[['claude-api','Claude API · web search','https://platform.claude.com/docs/en/agents-and-tools/tool-use/web-search-tool'],['gemini-api','Gemini API · Google Search','https://ai.google.dev/gemini-api/docs/google-search'],['perplexity-api','Perplexity Sonar','https://docs.perplexity.ai/docs/sonar/quickstart']].map(([id,name,href])=>({name,href,status:status?.directCollectors?.[id]?.ready?'Configured · not verified':status?.directCollectors?.[id]?.configured?'Collection disabled':'Not configured',ready:status?.directCollectors?.[id]?.ready,purpose:'Independent web-grounded research with original answers, source citations and model identity.',detail:'Requires a server-side API key, model ID, explicit enable switch and request allowance. API output is labeled separately from consumer-app observations. Configure provider billing limits separately; request allowance is not a dollar cap.'})),
 {name:'Analysis model',status:status?.analysisConfigured?'Connected':'Not configured',ready:status?.analysisConfigured,purpose:'Evidence-backed brand, sentiment and page-coverage assessment.',detail:`Total authorization remains $${status?.budget||15}; earlier reservations count toward the same limit. No automatic budget reset.`},
 {name:'Scheduled collection',status:status?.scheduling?'Ready to schedule':'Unavailable',ready:status?.scheduling,purpose:'Daily or weekly collection of your selected prompts and engines.',detail:'Configure a schedule in Prompt research & tracking. The durable queue records completion and failures. Local worker requires the preview server; the cloud worker runs independently after deployment.'},
 {name:'Google Analytics 4 + Search Console',status:status?.googleTrafficConfigured?'Server connector ready · property access required':'Property access required',ready:!!status?.googleTrafficConfigured,purpose:'Read-only AI referral sessions and Google organic search queries for the selected business.',detail:status?.googleTrafficConfigured?`Grant ${status.googleServiceAccount} read access in each verified Google property, then save the property IDs in AI visibility → Traffic.`:'A server-only service account plus read access to a GA4 property and verified Search Console property are required before real traffic reports can load.'},
 {name:'Keyword metrics',status:'Verified CSV imports',ready:true,purpose:'Monthly search volume and keyword difficulty from your chosen data provider.',detail:'Import exact prompt matches with Source, Volume, Difficulty, Date and Location. This is the selected workflow; no paid keyword connector or top-up is enabled.'}
 ];return <section className="ai-connectors" aria-labelledby="ai-connectors-title"><h3 id="ai-connectors-title">AI visibility connections</h3><p>Start with the essentials. Each connection has one job, and its status reflects what is actually available.</p><AiCloudAccount/><div className="aiv-connections">{services.map(service=><details key={service.name}><summary><span>{service.name}</span><span className={service.ready?'aiv-ready':''}>{service.ready?<Check size={14}/>:<Clock3 size={14}/>} {service.status}</span></summary><p><strong>{service.purpose}</strong></p><p>{service.detail}</p>{service.href&&<a className="ai-text-button" href={service.href} target="_blank" rel="noreferrer">Provider documentation<ArrowUpRight size={14}/></a>}</details>)}</div><h4 className="aiv-optional-title">Optional, after AI Insights</h4>{[
 ['Website request logs','Shows AI crawler activity on the business website. Requires its hosting/CDN logs; a crawler visit is not an answer citation.'],
 ['CMS publishing','Publishes approved content to the business’s chosen WordPress, Webflow, or other CMS. Not needed to measure AI visibility.'],
].map(([name,copy])=><details key={name}><summary><span>{name}</span><span>Optional · Not connected</span></summary><p>{copy}</p></details>)}</section>;}
