import React, {useState} from 'react';
export function AiCoverage({plan,rows,busy,remaining,onPrepare,onCollect,onEvidence}){
 const [intent,setIntent]=useState('All intents');
 const [engine,setEngine]=useState('chatgpt');
 const engineName={chatgpt:'ChatGPT Search',gemini:'Gemini',perplexity:'Perplexity'}[engine];
 const measured=new Set(rows.filter(r=>r.engine===engineName&&r.at.slice(0,10)===new Date().toISOString().slice(0,10)).map(r=>r.promptId).filter(Boolean));
 const gaps=rows.filter(r=>r.type==='Unbranded'&&!r.mentioned&&r.competitors?.length);
 const days=new Set(rows.map(r=>r.at.slice(0,10))).size;
 return <section className="panel aiv-scan-panel aiv-coverage" aria-label="Measurement coverage">
  <div className="aiv-heading"><div><h3>Build a clearer picture of your market</h3><p>{plan?`${measured.size} of ${plan.questions.length} planned questions collected today · ${days} observation ${days===1?'day':'days'} · ${engineName}`:'Prepare 24 buyer questions before expanding your measurement.'}</p></div>{!plan&&<button className="cs-button" disabled={busy} onClick={onPrepare}>{busy?'Preparing…':'Prepare question plan'}</button>}</div>
  <p>Early evidence · Engine coverage depends on completed collections. These results describe the questions collected, not every conversation about your market. More questions and repeated observations are needed for stable comparisons.</p>
  <div className="aiv-engine-coverage">{['ChatGPT Search','Gemini'].map(name=>{const subset=rows.filter(r=>r.engine===name);return <div key={name}><strong>{name}</strong><span>{subset.length} saved answers · {new Set(subset.map(r=>r.prompt)).size} questions</span></div>;})}</div><p>Compare engines on the same questions. Overall scores may be skewed when their question coverage differs; use the AI engine filter to inspect each separately.</p>
  {plan&&<details><summary>Review your question plan · {plan.questions.length} questions</summary><p><strong>Audience:</strong> {plan.audience}</p><label>Collection engine<select value={engine} onChange={e=>setEngine(e.target.value)}><option value="chatgpt">ChatGPT Search</option><option value="gemini">Gemini · provider availability varies</option></select></label><label>Filter by intent<select value={intent} onChange={e=>setIntent(e.target.value)}>{['All intents','Discovery','Comparison','Buying decisions','Use cases'].map(i=><option key={i}>{i}</option>)}</select></label><div className="ai-table-scroll" tabIndex={0} aria-label="Planned buyer questions"><table><thead><tr><th>Question</th><th>Intent</th><th>Collection</th></tr></thead><tbody>{plan.questions.filter(q=>intent==='All intents'||q.intent===intent).map(q=><tr key={q.id}><td>{q.text}<small>{q.topic}</small></td><td>{q.intent}</td><td><button className="cs-button" disabled={busy||measured.has(q.id)||remaining===0} onClick={()=>onCollect(q.id,engine)}>{measured.has(q.id)?'Collected today':'Collect answer'}</button></td></tr>)}</tbody></table></div><p>Each new answer uses one free search credit plus capped analysis. Additional engines depend on provider availability; failed requests never count as observations. Same-day requests reuse evidence. Collect again on another UTC day to build history. {remaining} local search attempts remain.</p></details>}
  <details><summary>Where competitors appear without you · {gaps.length} answers</summary>{gaps.length?gaps.map(r=><article key={r.id}><h4>{r.prompt}</h4><p>Mentioned: {r.competitors.join(', ')}</p><p>Next step: review the cited pages and compare their coverage with your relevant product or service page. This is a research lead, not proof of why the AI omitted your brand.</p><button className="ai-text-button" onClick={()=>onEvidence(r)}>Review answer and sources →</button></article>):<p>No competitor-only mentions found in collected answers. This does not establish that no gaps exist.</p>}</details>
 </section>;
}
