import {aiFetch} from './ai-cloud';
import {MeasurementReview} from './MeasurementReview';
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowUpRight, Download, Globe2, Eye, Link2, MessageSquare, ArrowRight, X, SlidersHorizontal, Search, BookOpen } from 'lucide-react';
import { insightTabs, summarizeAnswers, filterAnswers, sampleAnswers, brandRankings } from './ai-insights-data';
import './ai-tracking-dialog.css';
import { AiCoverage } from './AiCoverage';
import { AiVisibilityReport } from './AiVisibilityReport';
const percent = value => value === null ? '—' : `${value.toFixed(1)}%`;
function Panel({ title, note, children, className = '' }) { return <section className={`panel aiv-panel ${className}`}><div className="aiv-heading"><h3>{title}</h3>{note && <span>{note}</span>}</div>{children}</section>; }
function Empty({ title = 'Your first scan starts the story.', children, onSettings }) { return <div className="aiv-chart-empty"><Eye size={26}/><h3>{title}</h3><p>{children || 'Connect an answer collector to see how often your business appears. No visibility measurements have been collected yet.'}</p>{onSettings && <button className="cs-button" onClick={onSettings}>Set up monitoring<ArrowRight size={16}/></button>}</div>; }
function Trend({ rows, field = 'mentioned' }) {
  const grouped = new Map(); rows.forEach(row => { const day = row.at.slice(0, 10); const value = grouped.get(day) || { total: 0, count: 0 }; value.total++; if (row[field]) value.count++; grouped.set(day, value); });
  const data = [...grouped].sort(([a], [b]) => a.localeCompare(b));
  if (!data.length) return <Empty/>;
  const points = data.map(([, v], i) => `${50 + i / Math.max(1, data.length - 1) * 560},${190 - v.count / v.total * 155}`).join(' ');
  return <div className="aiv-line-chart"><svg viewBox="0 0 650 220" role="img" aria-label={`Daily ${field === 'cited' ? 'citation' : 'mention'} rates: ${data.map(([d, v]) => `${d}: ${(v.count / v.total * 100).toFixed(0)}%`).join(', ')}`}>
    {[0, 50, 100].map(value => <g key={value}><line x1="50" x2="610" y1={190 - value * 1.55} y2={190 - value * 1.55}/><text x="6" y={194 - value * 1.55}>{value}%</text></g>)}<polyline points={points}/>{data.map(([day,v],i) => <circle key={day} cx={50 + i / Math.max(1,data.length-1)*560} cy={190-v.count/v.total*155} r="4"/>)}</svg><div><span>{new Date(data[0][0]).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span><span>Daily observations</span><span>{new Date(data.at(-1)[0]).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span></div></div>;
}
export function AiInsights({ business, onSettings, onResearch }) {
  const [qualityOpen,setQualityOpen]=useState(false),[measurementProfile,setMeasurementProfile]=useState(null),[trackedNames,setTrackedNames]=useState([]);
  const [trackingOpen,setTrackingOpen]=useState(false);
  const trackingDialog=useRef(null);
  useEffect(()=>{const dialog=trackingDialog.current;if(!dialog)return;if(trackingOpen&&!dialog.open)dialog.showModal();else if(!trackingOpen&&dialog.open)dialog.close();},[trackingOpen]);
  const [tab, setTab] = useState(0), refs = useRef([]);
  const [preview, setPreview] = useState(false), [engine, setEngine] = useState('All engines'), [period, setPeriod] = useState(7), [topic, setTopic] = useState('All topics'), [type, setType] = useState('All prompts'), [query, setQuery] = useState(''), [evidence, setEvidence] = useState(null);
  const [cadence,setCadence]=useState('Daily'),[location,setLocation]=useState('All locations'),[selectedBrand,setSelectedBrand]=useState(business.name),[brandSearch,setBrandSearch]=useState(''),[learn,setLearn]=useState(false);
  const [competitorDraft,setCompetitorDraft]=useState(''),[competitorSaving,setCompetitorSaving]=useState(false),[competitorNotice,setCompetitorNotice]=useState('');
  const [live,setLive]=useState([]),[configured,setConfigured]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[scanError,setScanError]=useState(''),[remaining,setRemaining]=useState(null),[prompt,setPrompt]=useState(`What does ${business.name} at ${business.domain} offer? Cite your sources.`);
  const [plan,setPlan]=useState(null);
  const [analysisBudget,setAnalysisBudget]=useState(null);
  async function planAction(action,extra={}){if(busy)return;setBusy(true);setScanError('');try{const data=await callCollector(action,extra);setPlan(data.plan);setLive(data.answers);setRemaining(data.attemptsRemaining);setPreview(false);setType('Unbranded');}catch(e){setScanError(e.message);}finally{setBusy(false);}}
  const [report,setReport]=useState(null),[analysisConfigured,setAnalysisConfigured]=useState(false);
  async function buildReport(){if(busy)return;setBusy(true);setScanError('');try{const data=await callCollector('baseline');setLive(data.answers);setReport(data.report);setRemaining(data.attemptsRemaining);setCompetitorDraft((data.competitors||[]).join('\n'));setPreview(false);setType('Unbranded');setScanError(data.report?.error||'');if(data.report?.status==='complete')setTrackingOpen(false);}catch(e){setScanError(e.message);}finally{setBusy(false);}}
  async function callCollector(action, extra={}) {
    const response=await aiFetch('/api/ai/searchapi',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,business:{name:business.name,domain:business.domain,description:business.description,pages:business.pages?.map(p=>({url:p.url,title:p.title,description:p.description}))},prompt,...extra})});
    if(!response.headers.get('content-type')?.includes('application/json'))throw new Error('Live scans are available in the local preview only.');
    const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not load scans.');if(result.analysisBudget)setAnalysisBudget(result.analysisBudget);setMeasurementProfile(result.measurementProfile);setTrackedNames(result.competitors||[]);return result;
  }
  useEffect(()=>{let cancelled=false;callCollector('list').then(data=>{if(!cancelled){setPlan(data.plan);setReport(data.report);setAnalysisConfigured(data.analysisConfigured);if(data.report?.status==='complete')setType('Unbranded');setLive(data.answers);setCompetitorDraft((data.competitors||[]).join('\n'));setConfigured(data.configured);setRemaining(data.attemptsRemaining);if(!data.answers.length)setTrackingOpen(true);}}).catch(e=>{if(!cancelled)setScanError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[business.domain]);
  async function saveCompetitors(e){e.preventDefault();if(competitorSaving||busy)return;setCompetitorSaving(true);setCompetitorNotice('');try{const names=competitorDraft.split(/[,\n]/).map(s=>s.trim()).filter(Boolean);const data=await callCollector('competitors',{competitors:names});setLive(data.answers);setCompetitorDraft(data.competitors.join('\n'));setSelectedBrand(business.name);setPreview(false);setCompetitorNotice('Comparison updated across saved answers. No scan credits used.');}catch(e){setCompetitorNotice(e.message);}finally{setCompetitorSaving(false);}}
  async function scan(e){e.preventDefault();if(busy)return;setBusy(true);setScanError('');try{const data=await callCollector('scan');setLive(data.answers);setRemaining(data.attemptsRemaining);setPreview(false);setEngine('All engines');setTopic('All topics');setLocation('All locations');setType('All prompts');setEvidence(null);}catch(e){setScanError(e.message);}finally{setBusy(false);}}
  const all = useMemo(() => preview ? sampleAnswers(business) : live, [preview,business,live]);
  const rows = filterAnswers(all, { engine, period, topic, type, location });
  const stats = summarizeAnswers(rows);
  const rankings = brandRankings(rows, business.name);
  const ownShare = rankings.find(r=>r.own)?.sov ?? null;
  const topics = [...new Set(all.map(r=>r.topic))];
  const locations = [...new Set(all.map(r=>r.location))];
  const sourceDomains = [...new Set(rows.flatMap(r=>r.sources.map(url=>new URL(url).hostname.replace(/^www\./,''))))];
  const engines = [...new Set(all.map(r=>r.engine))];
  const visible = rows.filter(r => `${r.prompt} ${r.engine}`.toLowerCase().includes(query.toLowerCase()));
  function exportData() {
    const contents = { business: business.domain, dataset: preview?'synthetic-preview':'collected-answers', filters: { engine, period, topic, type, location, cadence, brand: selectedBrand }, answers: rows };
    const url = URL.createObjectURL(new Blob([JSON.stringify(contents,null,2)],{type:'application/json'})); const a=document.createElement('a'); a.href=url; a.download=preview?'sample-ai-insights.json':'ai-insights.json'; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000);
  }
  const breakdown = (names, key, metric = 'mentioned') => <div className="aiv-breakdown">{names.map(name => { const subset = rows.filter(r => r[key] === name); const rate = subset.length ? subset.filter(r => r[metric]).length / subset.length * 100 : null; return <div key={name}><span>{name}</span><div><i style={{width:`${rate || 0}%`}}/></div><strong>{percent(rate)}</strong><small>{subset.length} answers</small></div>; })}</div>;
  return <div className="aiv-insights">
    <div className="avr-toolbar"><label className="avr-toolbar-search"><Search size={16}/><input aria-label="Find a brand in rankings" placeholder="Find a brand…" value={brandSearch} onChange={e=>{setBrandSearch(e.target.value);setTab(0);}}/></label><button className="cs-button" aria-expanded={learn} aria-controls="avr-learn" onClick={()=>setLearn(!learn)}><BookOpen size={15}/>Learn</button><button className="cs-button" onClick={exportData} disabled={!rows.length}><Download size={15}/>Export {preview?'sample':'results'}</button></div>
    {learn&&<section id="avr-learn" className="avr-help"><p><strong>Visibility</strong> is the percentage of collected answers that mention a brand. <strong>Share of voice</strong> is its share of mentions across all compared brands. <strong>Average position</strong> only includes answers with an explicit ranking; a lower number is better.</p><p>Choose a brand in Rankings to compare it. Switch between chart views or open Share of voice details. Sample preview uses synthetic answers; manual live scans use SearchAPI. Mentions are exact-name matches; share of voice is calculated within your chosen competitor list, counting each brand at most once per answer. Competitor reports use model classifications checked against quoted answer evidence. Manual scans use name matching and leave sentiment and position unassessed. Changing the list reanalyzes saved answers; it does not recreate historical tracking lists.</p><button className="ai-text-button" onClick={onSettings}>Set up monitoring<ArrowRight size={15}/></button></section>}
    <div className="ai-subtabs aiv-insight-tabs" role="tablist" aria-label="AI Insights views">{insightTabs.map((name,i) => <button key={name} ref={el=>refs.current[i]=el} role="tab" id={`aiv-tab-${i}`} aria-controls="aiv-insight-panel" aria-selected={tab===i} tabIndex={tab===i?0:-1} onClick={()=>{setTab(i);setEvidence(null);}} onKeyDown={e=>{const next=e.key==='ArrowRight'?(i+1)%insightTabs.length:e.key==='ArrowLeft'?(i+insightTabs.length-1)%insightTabs.length:e.key==='Home'?0:e.key==='End'?insightTabs.length-1:null;if(next!==null){e.preventDefault();setTab(next);setEvidence(null);refs.current[next].focus();}}}>{name}</button>)}</div>
    <div className="aiv-filters avr-filters"><label><span className="aiv-sr-only">Compare brand</span><select className="avr-brand-select" value={rankings.some(r=>r.name===selectedBrand)?selectedBrand:business.name} onChange={e=>setSelectedBrand(e.target.value)}>{rankings.map(r=><option key={r.name}>{r.name}</option>)}</select></label><label><span className="aiv-sr-only">Date range</span><select value={period} onChange={e=>setPeriod(Number(e.target.value))}><option value={7}>Last 7 days</option><option value={14}>Last 14 days</option></select></label><label><span className="aiv-sr-only">Chart interval</span><select value={cadence} onChange={e=>setCadence(e.target.value)}><option>Daily</option><option>Weekly</option></select></label><span className="avr-filter-spacer"/><label><span className="aiv-sr-only">Prompt type</span><select value={type} onChange={e=>setType(e.target.value)}><option value="All prompts">Branded &amp; unbranded</option><option>Branded</option><option>Unbranded</option></select></label><label><span className="aiv-sr-only">AI engine</span><select value={engine} onChange={e=>setEngine(e.target.value)}><option value="All engines">All models</option>{engines.map(v=><option key={v}>{v}</option>)}</select></label><label><span className="aiv-sr-only">Topic</span><select value={topic} onChange={e=>setTopic(e.target.value)}><option>All topics</option>{topics.map(v=><option key={v}>{v}</option>)}</select></label><label><span className="aiv-sr-only">Location</span><select value={location} onChange={e=>setLocation(e.target.value)}><option>All locations</option>{locations.map(v=><option key={v}>{v}</option>)}</select></label></div>
    <div className="aiv-report-status"><span role="status">{busy?'Analysis in progress…':loading?'Loading insights…':preview?'Sample data':live.length?`Updated ${new Date(Math.max(...live.map(r=>new Date(r.at).getTime()))).toLocaleString()}`:'Ready to analyze your business'}</span><button className="ai-text-button" onClick={()=>setQualityOpen(true)}>Data quality · {stats.total} answers</button><button className="ai-text-button" onClick={()=>setTrackingOpen(true)}><SlidersHorizontal size={14}/>{live.length?'Manage tracking':'Set up analysis'}</button></div>
    {scanError&&!trackingOpen&&<p role="alert" className="aiv-panel-note">{scanError}</p>}
    {qualityOpen&&<MeasurementReview rows={rows} business={business} profile={measurementProfile} names={[business.name,...trackedNames]} onSave={profile=>callCollector('measurementProfile',{profile:{...profile,aliases:Object.fromEntries(Object.entries(profile.aliases).map(([name,list])=>[name,list.map(a=>a.trim()).filter(Boolean)]))}})} onClose={()=>setQualityOpen(false)}/>}
    <dialog ref={trackingDialog} className="aiv-tracking-dialog" aria-labelledby="tracking-title" onCancel={()=>setTrackingOpen(false)} onClick={e=>{if(e.target===trackingDialog.current)setTrackingOpen(false);}}>
      <header><div><h2 id="tracking-title">{live.length?'Manage tracking':'Set up AI Insights'}</h2><p>{business.name} · {business.domain}</p></div><button className="cs-button" aria-label="Close tracking setup" onClick={()=>setTrackingOpen(false)}><X size={18}/></button></header>
      {!live.length&&<p className="aiv-setup-intro">We’ll identify competitors, prepare buyer questions, and collect AI answers. Start with the competitor report below; your insights will open when it is ready.</p>}
      {busy&&<p role="status" className="aiv-setup-intro">Collecting and analyzing answers. You can close this dialog to view existing insights. Keep this page open until collection finishes.</p>}
    <div className={`aiv-data-notice avr-status ${preview?'sample':''}`}><div><span className="aiv-status-dot"/><strong>{preview?'Sample preview':loading?'Loading saved scans':configured?'SearchAPI · Free trial':'Collector unavailable'}</strong><span>{preview?'Synthetic data · Not measured business results.':'Collected answers · Saved in the connected monitoring store.'} {stats.total} {preview?'sample ':''}{stats.total===1?'answer':'answers'}.</span></div><label><input type="checkbox" checked={preview} onChange={e=>{setPreview(e.target.checked);setEngine('All engines');setTopic('All topics');setLocation('All locations');setType('All prompts');setSelectedBrand(business.name);setEvidence(null);}}/>Preview sample charts</label></div>
    <div className="ai-filter-row"><button className="cs-button" onClick={()=>{setTrackingOpen(false);onResearch();}}>Prompt research &amp; tracking<ArrowUpRight size={15}/></button></div>
    {!preview&&analysisConfigured&&<AiCoverage plan={plan} rows={live} busy={busy||loading||competitorSaving} remaining={remaining} onPrepare={()=>planAction('plan')} onCollect={(promptId,engine)=>planAction('collectPrompt',{promptId,engine})} onEvidence={row=>{setTrackingOpen(false);setTab(1);setEvidence(row);}}/>}
    <section className="panel aiv-scan-panel" aria-label="Competitor report"><div className="aiv-heading"><div><h3>Your market, in AI answers</h3><p>{report?.category||'Discover competitors and compare their visibility against your business.'}</p></div><button className="cs-button filled" disabled={busy||loading||competitorSaving||!configured||!analysisConfigured||report?.status==='complete'} onClick={buildReport}>{busy?'Building report…':report?.status==='complete'?'Report collected':report?'Resume report':'Build competitor report'}</button></div><p>ChatGPT Search · Up to 8 discovered competitors · 3 shared buyer questions · Up to 4 free search credits. Analysis uses the capped local pilot budget.</p>{report&&<p role="status">{report.completed.length} of 3 questions analyzed · {report.status==='complete'?'Collected '+new Date(report.finishedAt).toLocaleString():'Partial report — saved evidence is retained.'}</p>}{report?.error&&<p role="alert">{report.error}</p>}{report?.questions?.length>0&&<details><summary>Questions used for this comparison</summary><ol>{report.questions.map(q=><li key={q}>{q}</li>)}</ol></details>}</section>
    <section className="panel aiv-scan-panel" aria-label="Manual AI scan"><form onSubmit={scan}><label htmlFor="aiv-scan-question">Ask a question about your market</label><div><input id="aiv-scan-question" value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={1000} required disabled={busy} placeholder="Which tools help businesses improve AI search visibility?"/><button className="cs-button" disabled={busy||competitorSaving||loading||!configured||remaining===0||!prompt.trim()}>{busy?'Collecting answer…':'Run scan'}</button></div><p>ChatGPT web search · One trial request per scan · {remaining===null?'Checking pilot limit…':`${remaining} of 100 local trial attempts available`}. A small set of answers is not an overall visibility benchmark. Brand-specific questions test awareness; use category questions to test discovery.</p></form><details className="aiv-competitor-editor"><summary>Manage competitors <span>Compare the same answers · No extra credits</span></summary><form onSubmit={saveCompetitors}><label htmlFor="aiv-competitor-names">Tracked competitors</label><textarea id="aiv-competitor-names" value={competitorDraft} onChange={e=>setCompetitorDraft(e.target.value)} maxLength={1100} rows={4} placeholder="One brand name per line" disabled={busy||competitorSaving||loading}/><p>Up to 12 names, one per line. Names from your reference are suggested for Uplift AI; edit them to match your market. Zero means no exact-name mention in the collected answers. Model assessments are retained when the list is unchanged. Editing this list uses name matching; unsupported sentiment and positions stay empty.</p><button className="cs-button" disabled={busy||competitorSaving||loading}>{competitorSaving?'Updating…':'Update comparison'}</button><p role="status">{competitorNotice}</p></form></details><div role="status" aria-live="polite">{busy&&<p>Collecting and analyzing live answers. A competitor report can take several minutes. Keep this page open.</p>}{scanError&&<p role="alert">{scanError}</p>}</div></section>
    {analysisBudget&&!preview&&<p className="aiv-panel-note">Analysis budget: ${analysisBudget.limit.toFixed(2)} total · Estimated usage: ${analysisBudget.estimatedCost.toFixed(3)} · Conservative reservations: ${analysisBudget.reserved.toFixed(2)}. Search collection uses free credits.</p>}
      <footer><button className="cs-button filled" onClick={()=>setTrackingOpen(false)}>View insights</button><button className="ai-text-button" onClick={()=>{setTrackingOpen(false);onSettings();}}>Connections &amp; settings<ArrowUpRight size={15}/></button></footer>
    </dialog>
    <div id="aiv-insight-panel" role="tabpanel" aria-labelledby={`aiv-tab-${tab}`}>
      {tab===0 && <AiVisibilityReport report={report} rows={rows} business={business} period={period} cadence={cadence} selected={selectedBrand} setSelected={setSelectedBrand} preview={preview} search={brandSearch}/>}
      {tab===1 && <><div className="aiv-analysis-grid"><Panel title="Citation rate"><div className="aiv-big-number">{percent(stats.citationRate)}<span>Answers linking to your website</span></div><Trend rows={rows} field="cited"/></Panel><Panel title="Average recommendation position"><div className="aiv-big-number">{stats.position===null?'—':`#${stats.position.toFixed(1)}`}<span>{rows.length?'Among explicitly ranked answers':'No ranked answers collected'}</span></div><p className="aiv-panel-note">An answer without a ranking is excluded from this average. Missing results are never treated as zero.</p></Panel></div><Panel title="Answer explorer" note={preview?'Synthetic evidence':'Collected response evidence'}><input className="aiv-search" aria-label="Search AI answers" placeholder="Search questions or engines…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="ai-table-scroll" tabIndex={0} aria-label="AI answer results"><table><thead><tr>{['Question','Engine','Mention','Citation','Evidence'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visible.slice(0,20).map(row=><tr key={row.id}><td>{row.prompt}</td><td>{row.engine}</td><td>{row.mentioned?'Yes':'No'}</td><td>{row.cited?'Yes':'No'}</td><td><button className="ai-text-button" onClick={()=>setEvidence(row)}>View answer<ArrowUpRight size={14}/></button></td></tr>)}</tbody></table></div>{!visible.length&&<p className="aiv-panel-note">{rows.length?'No answers match this search.':'No answers match these filters. Run a scan or adjust the filters.'}</p>}{visible.length>20&&<p className="aiv-panel-note">Showing the first 20 of {visible.length} answers. Export includes all filtered answers.</p>}{evidence&&<section className="aiv-evidence" aria-label="Answer evidence"><div className="aiv-heading"><h3>{evidence.engine} · {preview?'Sample answer':'Collected answer'}</h3><button className="cs-button" onClick={()=>setEvidence(null)} aria-label="Close answer evidence"><X size={16}/></button></div><p>{evidence.answer}</p><p>Tracked competitors mentioned: {evidence.competitors?.join(', ')||'None detected'}. {evidence.assessmentMethod||'Exact-name matching'}; review the answer for ambiguous names.</p><p>{evidence.method} · {new Date(evidence.at).toLocaleString()}</p><strong>{preview?'Example sources':'Cited sources'}</strong><ul>{evidence.sources.map(url=><li key={url}><a href={url} target="_blank" rel="noreferrer">{url}</a></li>)}</ul></section>}</Panel></>}
      {tab===2 && <div className="aiv-analysis-grid"><Panel title="How your business is described" note="Among answers mentioning your brand">{rows.some(r=>['Positive','Neutral','Negative'].includes(r.sentiment)) ? <div className="aiv-sentiment">{['Positive','Neutral','Negative'].map((label,i)=>{const count=rows.filter(r=>r.sentiment===label).length;return <div key={label}><div className={`aiv-sentiment-bar tone-${i}`} style={{height:`${count/Math.max(1,stats.mentions)*190}px`}}/><strong>{count}</strong><span>{label}</span></div>;})}</div>:<Empty title="Sentiment has not been assessed."/>}<p className="aiv-panel-note">Sentiment is a classification of the answer, not a customer review or a verified fact.</p></Panel><Panel title="Factual review"><Empty title="Review claims when answers arrive.">Statements will retain the original answer and source. Marking a statement incorrect will not change an external AI model.</Empty></Panel></div>}
      {tab===3 && <Panel title="Sources behind AI answers" note="Cited URLs, grouped by domain">{rows.length ? <div className="ai-table-scroll" tabIndex={0} aria-label="Citation sources"><table><thead><tr><th>Source</th><th>Attribution</th><th>Answers citing it</th></tr></thead><tbody>{sourceDomains.map(domain=><tr key={domain}><td>{domain}</td><td>{domain===business.domain?'Owned website':preview?'Illustrative third-party source':'Third-party source'}</td><td>{rows.filter(r=>r.sources.some(url=>new URL(url).hostname.replace(/^www\./,'')===domain)).length}</td></tr>)}</tbody></table></div>:<Empty title="See which websites AI consults." onSettings={onSettings}>Source URLs will come from captured answers. We won’t count a whole social or review platform as your brand’s source.</Empty>}</Panel>}
      {tab===4 && <div className="aiv-analysis-grid"><Panel title="Visibility by topic">{breakdown(topics,'topic')}<button className="ai-text-button" onClick={onResearch}>Manage prompt topics<ArrowUpRight size={15}/></button></Panel><Panel title="Context from your website" note="Headings, not measured topic rankings">{business.headings.length ? <ul className="aiv-heading-list">{business.headings.slice(0,6).map((h,i)=><li key={i}>{h}</li>)}</ul>:<p>No headings were extracted. Add your topics in the prompt library.</p>}</Panel></div>}
      {tab===5 && <Panel title="Searches behind the answer" note="Only queries explicitly returned by the collector">{rows.some(r=>r.fanout.length) ? <div className="aiv-fanout">{rows.filter(r=>r.fanout.length).slice(0,4).map(row=><details key={row.id}><summary>{row.prompt}<span>{row.fanout.length} {preview?'sample ':''}queries</span></summary><ul>{row.fanout.map(q=><li key={q}>{q}</li>)}</ul></details>)}</div>:<Empty title="Follow the searches that support an answer.">Query fanout appears only when the provider returns it. It does not expose a model’s private reasoning.</Empty>}</Panel>}
      {tab===6 && <Panel title="Visibility by market" note="The scan location, not the visitor’s location">{breakdown(locations,'location')}<p className="aiv-panel-note">Regional comparisons need collection support and enough observations in each market. The current ChatGPT collector does not select or verify a geographic market.</p></Panel>}
    </div>
    <footer className="aiv-footer">{preview?'Sample data only':`${stats.total} answers in this view`}<button className="ai-text-button" onClick={onSettings}>Manage connections<ArrowUpRight size={15}/></button></footer>
  </div>;
}
