import {InsightPages} from './InsightPages';
import {aiFetch} from './ai-cloud';
import {MeasurementReview} from './MeasurementReview';
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowUpRight, Download, Globe2, Eye, Link2, MessageSquare, ArrowRight, X, SlidersHorizontal, Search, BookOpen } from 'lucide-react';
import { insightTabs, summarizeAnswers, filterAnswers, sampleAnswers, brandRankings } from './ai-insights-data';
import './ai-tracking-dialog.css';
import { AiCoverage } from './AiCoverage';
import { AiVisibilityReport } from './AiVisibilityReport';
import { LOCATION_REGIONS } from './location-regions';
const percent = value => value === null ? '—' : `${value.toFixed(1)}%`;
function Panel({ title, note, children, className = '' }) { return <section className={`panel aiv-panel ${className}`}><div className="aiv-heading"><h3>{title}</h3>{note && <span>{note}</span>}</div>{children}</section>; }
function Empty({ title = 'Your first scan starts the story.', children, onSettings }) { return <div className="aiv-chart-empty"><Eye size={26}/><h3>{title}</h3><p>{children || 'Connect an answer collector to see how often your business appears. No visibility measurements have been collected yet.'}</p>{onSettings && <button className="cs-button" onClick={onSettings}>Set up monitoring<ArrowRight size={16}/></button>}</div>; }
function Trend({ rows, field = 'mentioned' }) {
  const grouped = new Map(); rows.forEach(row => { const day = row.at.slice(0, 10); const value = grouped.get(day) || { total: 0, count: 0 }; value.total++; if (row[field]) value.count++; grouped.set(day, value); });
  const data = [...grouped].sort(([a], [b]) => a.localeCompare(b));
  if (!data.length) return <Empty/>;
  const points = data.map(([, v], i) => `${50 + i / Math.max(1, data.length - 1) * 560},${190 - v.count / v.total * 155}`).join(' ');
  return <div className="aiv-line-chart"><svg viewBox="0 0 650 220" role="img" aria-label={`Daily ${field === 'cited' ? 'citation' : 'mention'} rates: ${data.map(([d, v]) => `${d}: ${(v.count / v.total * 100).toFixed(0)}%`).join(', ')}`}>
    {[0, 50, 100].map(value => <g key={value}><line x1="50" x2="610" y1={190 - value * 1.55} y2={190 - value * 1.55}/><text x="6" y={194 - value * 1.55}>{value}%</text></g>)}<polyline points={points}/>{data.map(([day,v],i) => <circle key={day} cx={50 + i / Math.max(1,data.length-1)*560} cy={190-v.count/v.total*155} r="4"/>)}</svg><div><span>{new Date(data[0][0]).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span><span>Daily observations</span><span>{new Date(data.at(-1)[0]).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span></div></div>;
}
export function AiInsights({ business, onSettings, onResearch, onImprove }) {
  const [qualityOpen,setQualityOpen]=useState(false),[measurementProfile,setMeasurementProfile]=useState(null),[trackedNames,setTrackedNames]=useState([]);
  const [trackingOpen,setTrackingOpen]=useState(false);
  const [annotations,setAnnotations]=useState({}),[factReviews,setFactReviews]=useState({}),[library,setLibrary]=useState(null),[enriching,setEnriching]=useState(false),[classifying,setClassifying]=useState(false),[sourceMetadata,setSourceMetadata]=useState({});
  const trackingDialog=useRef(null);
  useEffect(()=>{const dialog=trackingDialog.current;if(!dialog)return;if(trackingOpen&&!dialog.open)dialog.showModal();else if(!trackingOpen&&dialog.open)dialog.close();},[trackingOpen]);
  const [tab, setTab] = useState(0), refs = useRef([]);
  const [preview, setPreview] = useState(false), [engine, setEngine] = useState('All engines'), [period, setPeriod] = useState(7), [topic, setTopic] = useState('All topics'), [type, setType] = useState('All prompts'), [query, setQuery] = useState(''), [evidence, setEvidence] = useState(null);
  const [cadence,setCadence]=useState('Daily'),[location,setLocation]=useState('All locations'),[mapLocation,setMapLocation]=useState(''),[selectedBrand,setSelectedBrand]=useState(business.name),[brandSearch,setBrandSearch]=useState(''),[learn,setLearn]=useState(false);
  useEffect(()=>setMapLocation(''),[business.domain]);
  const [competitorDraft,setCompetitorDraft]=useState(''),[competitorSaving,setCompetitorSaving]=useState(false),[competitorNotice,setCompetitorNotice]=useState('');
  const [live,setLive]=useState([]),[configured,setConfigured]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[scanError,setScanError]=useState(''),[remaining,setRemaining]=useState(null),[prompt,setPrompt]=useState(`What does ${business.name} at ${business.domain} offer? Cite your sources.`);
  const [plan,setPlan]=useState(null);
  const [benchmark,setBenchmark]=useState(null);
  const [entityAudit,setEntityAudit]=useState(null);
  const [scope,setScope]=useState('All collected');
  const [analysisBudget,setAnalysisBudget]=useState(null);
  const [pendingIdentityCount,setPendingIdentityCount]=useState(0);
  async function planAction(action,extra={}){if(busy)return;setBusy(true);setScanError('');try{const data=await callCollector(action,extra);setPlan(data.plan);setLive(data.answers);setRemaining(data.attemptsRemaining);setPreview(false);setType('Unbranded');}catch(e){setScanError(e.message);}finally{setBusy(false);}}
  const [report,setReport]=useState(null),[analysisConfigured,setAnalysisConfigured]=useState(false);
  async function buildReport(){if(busy)return;setBusy(true);setScanError('');try{const data=await callCollector('baseline');setLive(data.answers);setReport(data.report);setRemaining(data.attemptsRemaining);setCompetitorDraft((data.competitors||[]).join('\n'));setPreview(false);setType('Unbranded');setScanError(data.report?.error||'');if(data.report?.status==='complete')setTrackingOpen(false);}catch(e){setScanError(e.message);}finally{setBusy(false);}}
  async function callCollector(action, extra={}) {
    const response=await aiFetch('/api/ai/searchapi',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,business:{name:business.name,domain:business.domain,description:business.description,pages:business.pages?.map(p=>({url:p.url,title:p.title,description:p.description}))},prompt,...extra})});
    if(!response.headers.get('content-type')?.includes('application/json'))throw new Error('Live scans are available in the local preview only.');
    const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not load scans.');if(result.sourceMetadata)setSourceMetadata(result.sourceMetadata);if(result.insightAnnotations)setAnnotations(result.insightAnnotations);if(result.factReviews)setFactReviews(result.factReviews);if(result.library)setLibrary(result.library);if(result.analysisBudget)setAnalysisBudget(result.analysisBudget);setMeasurementProfile(result.measurementProfile);setTrackedNames(result.competitors||[]);setPendingIdentityCount(result.pendingIdentityCount||0);setBenchmark(result.benchmark||null);setEntityAudit(result.entityAudit||null);return result;
  }
  useEffect(()=>{let cancelled=false;callCollector('list').then(data=>{if(!cancelled){setPlan(data.plan);setReport(data.report);setAnalysisConfigured(data.analysisConfigured);setLive(data.answers);setCompetitorDraft((data.competitors||[]).join('\n'));setConfigured(data.configured);setRemaining(data.attemptsRemaining);setScope(data.benchmark?.completed?.length?'Benchmark only':'All collected');}}).catch(e=>{if(!cancelled)setScanError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[business.domain]);
  async function finishEntityAudit(){for(let i=0;i<8;i++){const data=await callCollector('auditEntities');setLive(data.answers);if(data.entityAudit?.status==='complete')return;}throw Error('Brand review needs another pass. Your measured answers are saved.');}
  async function reviewBrands(){if(busy)return;setBusy(true);setScanError('');try{await finishEntityAudit();}catch(e){setScanError(e.message);}finally{setBusy(false);}}
  const [analysisJob,setAnalysisJob]=useState(null);
  async function queueRequest(body){const response=await aiFetch('/api/ai/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||'Could not load analysis.');return data.job;}
  useEffect(()=>{let stopped=false;let timer;
   async function refresh(){try{const job=await queueRequest(analysisJob?.id?{action:'status',id:analysisJob.id}:{action:'status'});if(stopped)return;if(job?.domain===business.domain){setAnalysisJob(job);const data=await callCollector('list');if(stopped)return;setLive(data.answers);setPlan(data.plan);if(data.benchmark?.total===40&&data.benchmark.completed.length>0)setScope('Benchmark only');setScanError(job.status==='failed'?job.error:'');}}catch(e){if(!stopped)setScanError(e.message);}finally{if(!stopped)timer=setTimeout(refresh,10000);}}
   refresh();return()=>{stopped=true;clearTimeout(timer);};
  },[business.domain,analysisJob?.id]);

  async function saveCompetitors(e){e.preventDefault();if(competitorSaving||busy)return;setCompetitorSaving(true);setCompetitorNotice('');try{const names=competitorDraft.split(/[,\n]/).map(s=>s.trim()).filter(Boolean);const data=await callCollector('competitors',{competitors:names});setLive(data.answers);setCompetitorDraft(data.competitors.join('\n'));setSelectedBrand(business.name);setPreview(false);setCompetitorNotice('Comparison updated across saved answers. No scan credits used.');}catch(e){setCompetitorNotice(e.message);}finally{setCompetitorSaving(false);}}
  async function scan(e){e.preventDefault();if(busy)return;setBusy(true);setScanError('');try{const data=await callCollector('scan');setLive(data.answers);setRemaining(data.attemptsRemaining);setPreview(false);setEngine('All engines');setTopic('All topics');setLocation('All locations');setType('All prompts');setEvidence(null);}catch(e){setScanError(e.message);}finally{setBusy(false);}}
  async function enrich(){if(enriching)return;setEnriching(true);setScanError('');try{let previous=-1;for(let i=0;i<50;i++){const data=await callCollector('enrichInsights');const count=Object.keys(data.insightAnnotations||{}).length;if(count===previous||data.answers.every(r=>data.insightAnnotations?.[r.id]))break;previous=count;}}catch(e){setScanError(e.message);}finally{setEnriching(false);}}
  async function classifySources(){if(classifying)return;setClassifying(true);setScanError('');try{const data=await callCollector('classifySources');setLive(data.answers);}catch(e){setScanError(e.message);}finally{setClassifying(false);}}
  async function reassessIdentity(){if(busy)return;setBusy(true);setScanError('');try{const data=await callCollector('reassessIdentity');setLive(data.answers);setPreview(false);}catch(e){setScanError(e.message);}finally{setBusy(false);}}
  async function trackFanout(text){const current=await callCollector('list'),saved=current.library||{rows:[],revision:null};if(saved.rows.some(p=>p.text.trim().toLowerCase()===text.trim().toLowerCase()&&p.tracking&&p.status!=='archived'))return;const existing=saved.rows.find(p=>p.text.trim().toLowerCase()===text.trim().toLowerCase());const added={id:crypto.randomUUID(),text,topic:'Query fanout',topics:['Query fanout'],type:'Unbranded',intent:'Custom',status:'saved',tracking:true,createdAt:new Date().toISOString(),trackedAt:new Date().toISOString()};const next=existing?saved.rows.map(p=>p.id===existing.id?{...p,status:'saved',tracking:true}:p):[...saved.rows,added];await callCollector('library',{rows:next,revision:saved.revision});}
  const all = useMemo(() => preview ? sampleAnswers(business) : scope==='Benchmark only'&&benchmark ? live.filter(r=>r.benchmarkId===benchmark.startedAt) : live, [preview,business,live,scope,benchmark]);
  const rows = filterAnswers(all, { engine, period, topic, type, location });
  const cutoff=new Date();cutoff.setUTCHours(0,0,0,0);cutoff.setUTCDate(cutoff.getUTCDate()-period+1);
  const prior=filterAnswers(all,{engine,period,topic,type,location},new Date(cutoff.getTime()-1));
  const stats = summarizeAnswers(rows);
  const recommendationRows=rows.filter(r=>r.type!=='Branded'&&r.brandAssessment&&typeof r.recommended==='boolean');
  const recommendationCount=recommendationRows.filter(r=>r.recommended===true).length;
  const rankings = brandRankings(rows, business.name);
  const ownShare = rankings.find(r=>r.own)?.sov ?? null;
  const topics = [...new Set(all.map(r=>r.topic))];
  const locations = [...new Set(all.map(r=>r.location))];
  const sourceDomains = [...new Set(rows.flatMap(r=>r.sources.map(url=>new URL(url).hostname.replace(/^www\./,''))))];
  const engines = [...new Set(all.map(r=>r.engine))];
  const questionTypes = [...new Set(all.map(r=>r.type))];
  const collectionDays = new Set(all.map(r=>r.at?.slice(0,10)));
  const sevenDayCutoff = new Date();sevenDayCutoff.setUTCHours(0,0,0,0);sevenDayCutoff.setUTCDate(sevenDayCutoff.getUTCDate()-6);
  const hasOlderAnswers = all.some(r=>new Date(r.at)<sevenDayCutoff);
  const hasOtherMeasurements = !!benchmark&&live.some(r=>r.benchmarkId!==benchmark.startedAt);
  const filterLimited = !hasOtherMeasurements||!hasOlderAnswers||collectionDays.size<2||engines.length<2||locations.length<2;
  const filtersChanged = scope==='All collected'&&hasOtherMeasurements||selectedBrand!==business.name||period!==7||cadence!=='Daily'||type!=='All prompts'||engine!=='All engines'||topic!=='All topics'||location!=='All locations';
  function resetFilters(){setScope(benchmark?.completed?.length?'Benchmark only':'All collected');setSelectedBrand(business.name);setPeriod(7);setCadence('Daily');setType('All prompts');setEngine('All engines');setTopic('All topics');setLocation('All locations');}
  const visible = rows.filter(r => `${r.prompt} ${r.engine}`.toLowerCase().includes(query.toLowerCase()));
  function exportData() {
    const contents = { business: business.domain, dataset: preview?'synthetic-preview':'collected-answers', filters: { engine, period, topic, type, location, cadence, brand: selectedBrand }, answers: rows };
    const url = URL.createObjectURL(new Blob([JSON.stringify(contents,null,2)],{type:'application/json'})); const a=document.createElement('a'); a.href=url; a.download=preview?'sample-ai-insights.json':'ai-insights.json'; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000);
  }
  const breakdown = (names, key, metric = 'mentioned') => <div className="aiv-breakdown">{names.map(name => { const subset = rows.filter(r => r[key] === name); const rate = subset.length ? subset.filter(r => r[metric]).length / subset.length * 100 : null; return <div key={name}><span>{name}</span><div><i style={{width:`${rate || 0}%`}}/></div><strong>{percent(rate)}</strong><small>{subset.length} answers</small></div>; })}</div>;
  if(loading)return <section className="panel aiv-intake" role="status"><h3>Loading your AI Insights…</h3><p>Restoring collected answers and competitor results.</p></section>;
  if(!live.length&&!preview)return <section className="panel aiv-intake"><h3>Build your AI visibility report.</h3><p>We’ll find competitors and analyze real AI answers about {business.name}’s market.</p><button className="cs-button filled" disabled={busy} onClick={buildReport}>{busy?'Analyzing your business…':'Analyze website'}<ArrowRight size={16}/></button>{busy&&<p role="status">Collecting answers and checking the evidence. This can take a few minutes.</p>}{scanError&&<p className="aiv-error" role="alert">{scanError}</p>}</section>;
  return <div className="aiv-insights">
    <div className="avr-toolbar"><label className="avr-toolbar-search"><Search size={16}/><input aria-label="Find a brand in rankings" placeholder="Find a brand…" value={brandSearch} onChange={e=>{setBrandSearch(e.target.value);setTab(0);}}/></label><button className="cs-button" aria-expanded={learn} aria-controls="avr-learn" onClick={()=>setLearn(!learn)}><BookOpen size={15}/>Learn</button><button className="cs-button" onClick={exportData} disabled={!rows.length}><Download size={15}/>Export {preview?'sample':'results'}</button></div>
    {learn&&<section id="avr-learn" className="avr-help"><p><strong>Visibility</strong> is the percentage of answers mentioning a brand among answers where it was measured. <strong>Share of voice</strong> is its share of measured mentions across the tracked brands. <strong>Average position</strong> only includes answers with an explicit ranking; a lower number is better.</p><p>Choose a brand in Rankings to compare it. Switch between chart views or open Share of voice details. Sample preview uses synthetic answers; the benchmark collects web-grounded OpenAI answers and checks named brands against answer excerpts. A mention counts once per answer when the name or a verified alias appears in the answer. Sentiment and position stay empty when the answer does not support them. Keep the measurement set on “Benchmark only” for a consistent comparison across the same buyer questions.</p><button className="ai-text-button" onClick={onSettings}>Set up monitoring<ArrowRight size={15}/></button></section>}
    <div className="ai-subtabs aiv-insight-tabs" role="tablist" aria-label="AI Insights views">{insightTabs.map((name,i) => <button key={name} ref={el=>refs.current[i]=el} role="tab" id={`aiv-tab-${i}`} aria-controls="aiv-insight-panel" aria-selected={tab===i} tabIndex={tab===i?0:-1} onClick={()=>{setTab(i);setEvidence(null);}} onKeyDown={e=>{const next=e.key==='ArrowRight'?(i+1)%insightTabs.length:e.key==='ArrowLeft'?(i+insightTabs.length-1)%insightTabs.length:e.key==='Home'?0:e.key==='End'?insightTabs.length-1:null;if(next!==null){e.preventDefault();setTab(next);setEvidence(null);refs.current[next].focus();}}}>{name}</button>)}</div>
    <div className="aiv-filters avr-filters">
      {!preview&&benchmark&&<label><span className="aiv-sr-only">Measurement set</span><select value={scope} disabled={!hasOtherMeasurements} title={hasOtherMeasurements?'Choose which saved measurements to compare':'Only this benchmark has been measured'} onChange={e=>{setScope(e.target.value);setSelectedBrand(business.name);}}><option>Benchmark only</option>{hasOtherMeasurements&&<option>All collected</option>}</select></label>}
      <label><span className="aiv-sr-only">Compare brand</span><select className="avr-brand-select" value={rankings.some(r=>r.name===selectedBrand)?selectedBrand:business.name} disabled={rankings.length<2} onChange={e=>setSelectedBrand(e.target.value)}>{rankings.map(r=><option key={r.name}>{r.name}</option>)}</select></label>
      <label><span className="aiv-sr-only">Date range</span><select value={period} disabled={!hasOlderAnswers} title={hasOlderAnswers?'Choose a collection window':'All saved answers are within the last 7 days'} onChange={e=>setPeriod(Number(e.target.value))}><option value={7}>Last 7 days</option>{hasOlderAnswers&&<option value={14}>Last 14 days</option>}</select></label>
      <label><span className="aiv-sr-only">Chart interval</span><select value={cadence} disabled={collectionDays.size<2} title={collectionDays.size<2?'Only one collection date is available':'Group chart points by day or week'} onChange={e=>setCadence(e.target.value)}><option>Daily</option>{collectionDays.size>1&&<option>Weekly</option>}</select></label>
      <span className="avr-filter-spacer"/>
      <label><span className="aiv-sr-only">Prompt type</span><select value={type} disabled={questionTypes.length<2} title={questionTypes.length<2?'Only one prompt type has measured answers':'Filter by prompt type'} onChange={e=>setType(e.target.value)}><option value="All prompts">{questionTypes.length<2?`${questionTypes[0]||'All'} prompts`:'Branded & unbranded'}</option>{questionTypes.includes('Branded')&&<option>Branded</option>}{questionTypes.includes('Unbranded')&&<option>Unbranded</option>}</select></label>
      <label><span className="aiv-sr-only">AI engine</span><select value={engine} disabled={engines.length<2} title={engines.length<2?'Only one AI engine has measured answers':'Filter by AI engine'} onChange={e=>setEngine(e.target.value)}><option value="All engines">{engines.length<2?engines[0]||'All models':'All models'}</option>{engines.length>1&&engines.map(v=><option key={v}>{v}</option>)}</select></label>
      <label><span className="aiv-sr-only">Topic</span><select value={topic} disabled={topics.length<2} onChange={e=>setTopic(e.target.value)}><option>All topics</option>{topics.map(v=><option key={v}>{v}</option>)}</select></label>
      {tab===6?<label><span className="aiv-sr-only">View location on map</span><select value={mapLocation} onChange={e=>setMapLocation(e.target.value)}><option value="">Select a location</option>{LOCATION_REGIONS.map(name=><option key={name} value={name}>{name}</option>)}</select></label>:<label><span className="aiv-sr-only">Measured location</span><select value={location} disabled={locations.length<2} title={locations.length<2?'The saved answers have no location comparison':'Filter by measured location'} onChange={e=>setLocation(e.target.value)}><option value="All locations">{locations.length===1&&locations[0]==='Not specified'?'Location not recorded':'All locations'}</option>{locations.length>1&&locations.map(v=><option key={v}>{v}</option>)}</select></label>}
    </div>
    {(filtersChanged||filterLimited&&tab!==6)&&<div className="avr-filter-feedback" role="status"><span>{filtersChanged?`${stats.total} of ${all.length} answers in view${selectedBrand!==business.name?` · Comparing ${selectedBrand}`:''}.`:'Only measured choices are available. Date, model, and location comparisons need more varied answers.'}</span>{filtersChanged&&<button type="button" className="ai-text-button" onClick={resetFilters}>Reset filters</button>}</div>}
    <div className="aiv-report-status"><span role="status">{busy?'Analysis in progress…':loading?'Loading insights…':preview?'Sample data':live.length?`Updated ${new Date(Math.max(...live.map(r=>new Date(r.at).getTime()))).toLocaleString()}`:'Ready to analyze your business'}</span>{!preview&&stats.total>0&&stats.total<20&&<span className="aiv-early-sample" title="The score describes these collected answers, not every AI answer about this market.">Early sample · {stats.total} measured {stats.total===1?'answer':'answers'}</span>}<button className="ai-text-button" onClick={()=>setQualityOpen(true)}>Data quality · {stats.total} answers</button><button className="ai-text-button" onClick={()=>setTrackingOpen(true)}><SlidersHorizontal size={14}/>{live.length?'Manage tracking':'Set up analysis'}</button></div>

    {!preview&&<div className="aiv-recommendation-callout"><div><span>Explicit recommendations · unbranded buyer questions</span><strong>{recommendationRows.length?`${recommendationCount}/${recommendationRows.length}`:'—'}</strong><small>{recommendationRows.length?`${(recommendationCount/recommendationRows.length*100).toFixed(1)}% of assessed answers recommended ${business.name}`:'Collect assessed buyer answers to measure recommendations.'}</small></div><button className="cs-button" onClick={onImprove}>Find improvement opportunities<ArrowUpRight size={14}/></button></div>}
    {scanError&&!trackingOpen&&<p role="alert" className="aiv-panel-note">{scanError}</p>}
    {qualityOpen&&<MeasurementReview rows={rows} business={business} profile={measurementProfile} names={[business.name,...trackedNames]} onSave={profile=>callCollector('measurementProfile',{profile:{...profile,aliases:Object.fromEntries(Object.entries(profile.aliases).map(([name,list])=>[name,list.map(a=>a.trim()).filter(Boolean)]))}})} onClose={()=>setQualityOpen(false)}/>}
    <dialog ref={trackingDialog} className="aiv-tracking-dialog" aria-labelledby="tracking-title" onCancel={()=>setTrackingOpen(false)} onClick={e=>{if(e.target===trackingDialog.current)setTrackingOpen(false);}}>
      <header><div><h2 id="tracking-title">{live.length?'Manage tracking':'Set up AI Insights'}</h2><p>{business.name} · {business.domain}</p></div><button className="cs-button" aria-label="Close tracking setup" onClick={()=>setTrackingOpen(false)}><X size={18}/></button></header>
      {!live.length&&<p className="aiv-setup-intro">We’ll identify competitors, prepare buyer questions, and collect AI answers. Start with the competitor report below; your insights will open when it is ready.</p>}
      {busy&&<p role="status" className="aiv-setup-intro">Collecting and analyzing answers. You can close this dialog to view existing insights. Keep this page open until collection finishes.</p>}
    <div className={`aiv-data-notice avr-status ${preview?'sample':''}`}><div><span className="aiv-status-dot"/><strong>{preview?'Sample preview':loading?'Loading saved scans':analysisConfigured?'OpenAI benchmark ready':configured?'SearchAPI · Free trial':'Collector unavailable'}</strong><span>{preview?'Synthetic data · Not measured business results.':'Collected answers · Saved in the connected monitoring store.'} {stats.total} {preview?'sample ':''}{stats.total===1?'answer':'answers'}.</span></div><label><input type="checkbox" checked={preview} onChange={e=>{setPreview(e.target.checked);setEngine('All engines');setTopic('All topics');setLocation('All locations');setType('All prompts');setSelectedBrand(business.name);setEvidence(null);}}/>Preview sample charts</label></div>
    {!preview&&pendingIdentityCount>0&&<div className="aiv-data-notice" role="alert"><div><strong>Answer evidence needs review</strong><span>{pendingIdentityCount} saved {pendingIdentityCount===1?'answer is':'answers are'} excluded from scores until its brand mentions are checked against the website and verified aliases.</span></div><button className="cs-button filled" disabled={busy||!analysisConfigured} onClick={reassessIdentity}>{busy?'Re-assessing…':`Re-assess ${Math.min(3,pendingIdentityCount)} saved ${pendingIdentityCount===1?'answer':'answers'}`}</button></div>}
    <div className="ai-filter-row"><button className="cs-button" onClick={()=>{setTrackingOpen(false);onResearch();}}>Prompt research &amp; tracking<ArrowUpRight size={15}/></button></div>
    {!preview&&analysisConfigured&&<AiCoverage plan={plan} rows={live} busy={busy||loading||competitorSaving} remaining={remaining} onPrepare={()=>planAction('plan')} onCollect={(promptId,engine)=>planAction('collectPrompt',{promptId,engine})} onEvidence={row=>{setTrackingOpen(false);setTab(1);setEvidence(row);}}/>}
    <section className="panel aiv-scan-panel" aria-label="Competitor report"><div className="aiv-heading"><div><h3>Your market, in AI answers</h3><p>{report?.category||'Discover competitors and compare their visibility against your business.'}</p></div><button className="cs-button filled" disabled={busy||loading||competitorSaving||!configured||!analysisConfigured||report?.status==='complete'} onClick={buildReport}>{busy?'Building report…':report?.status==='complete'?'Report collected':report?'Resume report':'Build competitor report'}</button></div><p>ChatGPT Search · Up to 8 discovered competitors · 3 shared buyer questions · Up to 4 free search credits. Analysis uses the capped local pilot budget.</p>{report&&<p role="status">{report.completed.length} of 3 questions analyzed · {report.status==='complete'?'Collected '+new Date(report.finishedAt).toLocaleString():'Partial report — saved evidence is retained.'}</p>}{report?.error&&<p role="alert">{report.error}</p>}{report?.questions?.length>0&&<details><summary>Questions used for this comparison</summary><ol>{report.questions.map(q=><li key={q}>{q}</li>)}</ol></details>}</section>
    <section className="panel aiv-scan-panel" aria-label="Manual AI scan"><form onSubmit={scan}><label htmlFor="aiv-scan-question">Ask a question about your market</label><div><input id="aiv-scan-question" value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={1000} required disabled={busy} placeholder="Which tools help businesses improve AI search visibility?"/><button className="cs-button" disabled={busy||competitorSaving||loading||!configured||!analysisConfigured||remaining===0||!prompt.trim()}>{busy?'Collecting answer…':'Run scan'}</button></div><p>ChatGPT web search · One trial request per scan · {remaining===null?'Checking pilot limit…':`${remaining} of 100 local trial attempts available`}. Each answer is checked with OpenAI before entering the score. A small set of answers is not an overall visibility benchmark. Brand-specific questions test awareness; use category questions to test discovery.</p></form><details className="aiv-competitor-editor"><summary>Manage competitors <span>Compare the same answers · No extra credits</span></summary><form onSubmit={saveCompetitors}><label htmlFor="aiv-competitor-names">Tracked competitors</label><textarea id="aiv-competitor-names" value={competitorDraft} onChange={e=>setCompetitorDraft(e.target.value)} maxLength={1100} rows={4} placeholder="One brand name per line" disabled={busy||competitorSaving||loading}/><p>Up to 12 names, one per line. Names from your reference are suggested for Uplift AI; edit them to match your market. Zero means no exact-name mention in the collected answers. Model assessments are retained when the list is unchanged. Editing this list uses name matching; unsupported sentiment and positions stay empty.</p><button className="cs-button" disabled={busy||competitorSaving||loading}>{competitorSaving?'Updating…':'Update comparison'}</button><p role="status">{competitorNotice}</p></form></details><div role="status" aria-live="polite">{busy&&<p>Collecting and analyzing live answers. A competitor report can take several minutes. Keep this page open.</p>}{scanError&&<p role="alert">{scanError}</p>}</div></section>
    {analysisBudget&&!preview&&<p className="aiv-panel-note">Analysis budget: ${analysisBudget.limit.toFixed(2)} total · Estimated usage in this workspace: ${analysisBudget.estimatedCost.toFixed(3)} · Shared conservative reservations: ${analysisBudget.reserved.toFixed(2)}. OpenAI web searches use this capped budget; SearchAPI manual scans use free credits.</p>}
      <footer><button className="cs-button filled" onClick={()=>setTrackingOpen(false)}>View insights</button><button className="ai-text-button" onClick={()=>{setTrackingOpen(false);onSettings();}}>Connections &amp; settings<ArrowUpRight size={15}/></button></footer>
    </dialog>
    {tab===3&&!preview&&<div className="aiv-report-status"><span>{Object.keys(sourceMetadata).length} source pages processed · Unread or blocked pages stay unclassified</span><button className="cs-button" disabled={classifying||busy||!analysisConfigured||!live.flatMap(r=>r.sources||[]).some(url=>!sourceMetadata[url])} onClick={classifySources}>{classifying?'Reading sources…':'Classify next 3 sources'}</button></div>}
    {[1,2,4].includes(tab)&&!preview&&<div className="aiv-report-status"><span>{live.filter(r=>annotations[r.id]).length} of {live.length} answers analyzed for stages, attributes and claims</span><button className="cs-button" disabled={enriching||busy||!analysisConfigured||!live.some(r=>!annotations[r.id])} onClick={enrich}>{enriching?'Analyzing descriptions…':'Analyze descriptions'}</button></div>}
    <div id="aiv-insight-panel" role="tabpanel" aria-labelledby={`aiv-tab-${tab}`}>
      {tab===0 && <AiVisibilityReport report={report} rows={rows} business={business} period={period} cadence={cadence} selected={selectedBrand} setSelected={setSelectedBrand} preview={preview} search={brandSearch}/>}
      {tab>0&&<InsightPages key={business.domain} tab={tab} rows={rows} prior={prior} business={business} brand={selectedBrand} cadence={cadence} plan={plan} selectedLocation={mapLocation} onSelectLocation={setMapLocation} annotations={preview?{}:annotations} reviews={preview?{}:factReviews} library={library?.rows||[]} sourceMetadata={preview?{}:sourceMetadata} onReview={(f,verdict)=>callCollector('reviewFact',{answerId:f.row.id,quote:f.quote,verdict})} onTrack={trackFanout} evidence={evidence} onClearEvidence={()=>setEvidence(null)}/>}
    </div>
    <footer className="aiv-footer">{preview?'Sample data only':`${stats.total} answers in this view`}<button className="ai-text-button" onClick={onSettings}>Manage connections<ArrowUpRight size={15}/></button></footer>
  </div>;
}
