import {ResearchFindings} from './ResearchFindings';
import {PromptSchedule} from './PromptSchedule';
import {aiFetch} from './ai-cloud';
import React,{useState,useEffect,useRef} from 'react';
import {Plus,Search,Download,Pencil,ArrowUpRight,ChevronDown,Columns3,Sparkles,FolderOpen,X} from 'lucide-react';
import {PROMPT_STORAGE_KEY,readPromptLibrary,normalizePrompt} from './ai-prompt-data';
import {businessSuggestions} from './ai-business';
import {promptMetrics,promptReportCsv,keywordImportTemplate,mergeCollectedPrompts,groupPromptMetrics} from './prompt-report';
import {parseKeywordCsv} from './prompt-keywords';
import {BrandLogo} from './BrandLogo';
import {resolveBrandDomain} from './brand-domains';
import {reportMetrics} from './ai-insights-data';
import {PromptDetail} from './PromptDetail';
import './ai-research.css';
import './prompt-workspace.css';
const columnLabels={visibility:'Visibility Score',position:'Avg Position',sentiment:'Sentiment',visibilityRank:'Visibility Rank',citationShare:'Citation Share',citationRank:'Citation Rank',topic:'Topic',type:'Branded',volume:'Volume',difficulty:'Difficulty',mentions:'Mentions',location:'Location',coverage:'Page Coverage',intent:'Intent',created:'Created',tracked:'Tracked'};
const statusOf=p=>p.status==='archived'?'Archived':p.tracking?'Active':'Proposed';
const value=(n,suffix='')=>n==null?'—':`${n.toFixed(1)}${suffix}`;
export function AiPromptResearch({business,onToast,onSettings}){
 const [collectionEngine,setCollectionEngine]=useState('chatgpt');
 const storageKey=`${PROMPT_STORAGE_KEY}:${business.domain}`;
 const [initial]=useState(()=>readPromptLibrary(localStorage,storageKey));
 const [saved,setSaved]=useState(initial.rows),[error,setError]=useState(initial.error),[collection,setCollection]=useState(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState('');
 const [mode,setMode]=useState('Your prompts'),[status,setStatus]=useState('Active'),[topic,setTopic]=useState('All topics'),[query,setQuery]=useState(''),[type,setType]=useState('All types'),[intent,setIntent]=useState('All intents'),[days,setDays]=useState(30),[group,setGroup]=useState(true),[closed,setClosed]=useState(new Set()),[selection,setSelection]=useState(new Set()),[sort,setSort]=useState({key:'text',asc:true}),[columns,setColumns]=useState(Object.fromEntries(Object.keys(columnLabels).map(key=>[key,['visibility','position','sentiment','topic','type','volume','difficulty','mentions'].includes(key)]))),[detail,setDetail]=useState(null),[editor,setEditor]=useState(null),[extraTopics,setExtraTopics]=useState(()=>{try{return JSON.parse(localStorage.getItem(storageKey+':topics'))||[];}catch{return [];}}),[newTopic,setNewTopic]=useState(null);
 const editorRef=useRef(null), importRef=useRef(null),revision=useRef(0);
 const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 async function call(action,extra={}){const r=await aiFetch('/api/ai/searchapi',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,business:{name:business.name,domain:business.domain,description:business.description?.slice(0,1500)},...extra})});const d=await r.json();if(!r.ok)throw Error(d.error||'The request could not be completed.');return d;}
 useEffect(()=>{let active=true;call('list').then(d=>{if(active){setCollection(d);if(d.library){revision.current=d.library.revision;setSaved(d.library.rows);}else if(initial.rows.length){call('library',{rows:initial.rows,revision:0}).then(next=>{if(active){revision.current=next.library.revision;setCollection(next);}}).catch(e=>{if(active)setError(e.message);});}}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[business.domain]);
 useEffect(()=>{if(editor)editorRef.current?.showModal();},[!!editor]);
 async function persist(next){if(initial.error)return false;try{const data=await call('library',{rows:next,revision:revision.current});revision.current=data.library.revision;setCollection(data);setSaved(next);try{localStorage.setItem(storageKey,JSON.stringify(next));}catch{onToast('Prompts saved to the server; this browser cannot keep an offline copy.');}return true;}catch(e){setError(e.message);return false;}}

 const all=mergeCollectedPrompts(saved,collection?.plan?.questions||businessSuggestions(business),collection?.answers||[]).map(p=>({...p,coverage:collection?.coverage?.[p.text]})),topics=[...new Set([...all.flatMap(p=>p.topics||[p.topic]),...extraTopics])].sort();
 const answers=collection?.answers||[];
 const metrics=p=>{const m=promptMetrics(p,answers,business,days);const brands=reportMetrics(m.history,business.name);m.visibilityRank=m.visibility!=null?1+brands.filter(b=>b.visibility>m.visibility).length:null;const domains=brands.map(b=>({name:b.name,domain:domainFor(b.name)}));if(m.history.length&&domains.every(b=>b.domain)){const counts=domains.map(b=>({...b,count:m.history.filter(a=>(a.sources||[]).some(url=>{try{const h=new URL(url).hostname.replace(/^www\./,'');return h===b.domain||h.endsWith('.'+b.domain);}catch{return false;}})).length}));const own=counts.find(b=>b.name===business.name),total=counts.reduce((n,b)=>n+b.count,0);m.citationShare=total?own.count/total*100:null;m.citationRank=total?1+counts.filter(b=>b.count>own.count).length:null;}return m;};
 const sources=[...(collection?.report?.discovery?.sources||[]),...answers.flatMap(a=>a.sources||[])];
 const domainFor=name=>name===business.name?business.domain:resolveBrandDomain(name,sources,collection?.report?.suggestions);
 const visible=all.filter(p=>statusOf(p)===status&&(topic==='All topics'||(p.topics||[p.topic]).includes(topic))&&(type==='All types'||p.type===type)&&(intent==='All intents'||(p.intent||'Custom')===intent)&&`${p.text} ${p.topic}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>{const sortValue=p=>['text','topic','type','intent'].includes(sort.key)?p[sort.key]:['volume','difficulty'].includes(sort.key)?p.keywordData?.[sort.key]:sort.key==='created'?p.createdAt:sort.key==='tracked'?(p.trackedAt||metrics(p).history.at(-1)?.at):sort.key==='location'?(p.keywordData?.location||metrics(p).latest?.location):sort.key==='mentions'?metrics(p).brands.length:sort.key==='coverage'?p.coverage?.status:metrics(p)[sort.key];const av=sortValue(a),bv=sortValue(b);if(av==null)return bv==null?0:1;if(bv==null)return -1;return (typeof av==='string'?av.localeCompare(bv):av-bv)*(sort.asc?1:-1);});
 const selected=visible.filter(p=>selection.has(p.id));
 const groups=group?[...new Set(visible.flatMap(p=>p.topics||[p.topic]))].map(t=>[t,visible.filter(p=>(p.topics||[p.topic]).includes(t))]):[['',visible]];
 const directSelected=collectionEngine.endsWith('-api');
 const ready=(directSelected?collection?.directCollectors?.[collectionEngine]?.ready:collection?.configured)&&collection?.analysisConfigured;
 const remaining=directSelected?(collection?.directCollectors?.[collectionEngine]?.remaining||0):(collection?.attemptsRemaining||0);
 async function update(items,patch){const next=[...saved];for(const p of items){const idx=next.findIndex(r=>r.id===p.id);const row={...p,...patch,trackedAt:patch.tracking?(p.trackedAt||new Date().toISOString()):p.trackedAt,virtual:undefined};if(idx>=0)next[idx]=row;else next.push(row);}if(await persist(next)){setSelection(new Set());onToast(`${items.length} prompt${items.length===1?'':'s'} updated.`);}}
 async function research(){if(busy)return;setBusy(true);setError('');setProgress('Researching buyer questions…');try{const data=await call('plan');if(alive.current){setCollection(data);setMode('Prompt research');setGroup(false);setStatus('Proposed');setTopic('All topics');}}catch(e){if(alive.current)setError(e.message);}finally{if(alive.current){setBusy(false);setProgress('');}}}
 async function collect(items){if(busy||!items.length)return;setBusy(true);setError('');try{for(let i=0;i<items.length;i++){if(!alive.current)break;setProgress(`Collecting ${i+1} of ${items.length} · ${items[i].text}`);const data=await call('trackPrompt',{engine:collectionEngine,question:{text:items[i].text,topic:items[i].topic,type:items[i].type}});if(alive.current)setCollection(data);}}catch(e){if(alive.current)setError(e.message);}finally{if(alive.current){setBusy(false);setProgress('');}}}
 async function inspectCoverage(){if(busy||!selected.length)return;setBusy(true);setError('');setProgress('Reading your website and checking question coverage…');try{setCollection(await call('coverage',{questions:selected.map(p=>({text:p.text}))}));setColumns(c=>({...c,coverage:true}));}catch(e){setError(e.message);}finally{setBusy(false);setProgress('');}}
 async function schedulePrompts(schedule){setBusy(true);setError('');try{setCollection(await call('schedule',{schedule}));onToast(schedule.enabled?'Schedule saved.':'Schedule paused.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function importKeywords(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>1_000_000)throw Error('Use a CSV smaller than 1 MB.');const imported=parseKeywordCsv(await file.text());const matched=all.filter(p=>imported.some(k=>k.key===normalizePrompt(p.text)));if(!matched.length)throw Error('No prompts matched. Use the exact prompt text from this library.');const next=[...saved];for(const p of matched){const row={...p,virtual:undefined,keywordData:imported.find(k=>k.key===normalizePrompt(p.text))};const i=next.findIndex(r=>r.id===p.id);if(i<0)next.push(row);else next[i]=row;}if(await persist(next)){setError('');onToast(`Imported keyword data for ${matched.length} prompts. ${imported.length-matched.length} unmatched rows skipped.`);}}catch(e){setError(e.message);}}
 function downloadKeywordTemplate(){const url=URL.createObjectURL(new Blob(['\uFEFF'+keywordImportTemplate(visible)],{type:'text/csv;charset=utf-8;'}));const link=document.createElement('a');link.href=url;link.download=`${business.domain}-keyword-import.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function exportResults(){const url=URL.createObjectURL(new Blob(['\uFEFF'+promptReportCsv(visible,metrics)],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`${business.domain}-prompts.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function submit(e){e.preventDefault();const texts=editor.text.split('\n').map(t=>t.trim()).filter(Boolean);if(!texts.length||texts.length>100||texts.some(t=>t.length>500)){setError('Use 1–100 prompts, each up to 500 characters.');return;}const next=[...saved],seen=new Set(all.filter(p=>p.id!==editor.id).map(p=>normalizePrompt(p.text)));if(editor.id&&(texts.length!==1||seen.has(normalizePrompt(texts[0])))){setError('Use one unique question when editing a prompt.');return;}for(const text of texts){if(seen.has(normalizePrompt(text)))continue;seen.add(normalizePrompt(text));const row={...editor,text,id:editor.id||crypto.randomUUID(),topic:editor.topic.split(',')[0].trim().slice(0,80)||'General',topics:editor.topic.split(',').map(t=>t.trim().slice(0,80)).filter(Boolean),createdAt:editor.createdAt||new Date().toISOString(),status:'saved',tracking:!!editor.tracking,virtual:undefined};const i=next.findIndex(p=>p.id===row.id);if(i>=0)next[i]=row;else next.push(row);}if(await persist(next)){setEditor(null);setError('');setStatus(editor.tracking?'Active':'Proposed');setTopic('All topics');}}
 const openEditor=(p={})=>{setError('');setEditor({text:'',type:'Unbranded',...p,topic:p.topics?.join(', ')||p.topic||(topic==='All topics'?'':topic)});};
 const enabled=Object.keys(columns).filter(k=>columns[k]);
 const unavailable=label=><span className="pr-unavailable" title={`${label} is not supplied by the connected collector`} aria-label={`${label}: unavailable`}>—</span>;
 function cell(p,m,key){
  if(key==='visibility')return <button className="ai-text-button" title={`${business.name}: ${m.mentions||0} mentions in ${m.sampleSize||0} assessed answers. Click for evidence.`} onClick={()=>setDetail(p)}><span className="pr-score-badge">{m.visibility==null?'Not measured':value(m.visibility,'%')}</span><small>{m.sampleSize?`${m.mentions}/${m.sampleSize} answers`:'View collection'}</small></button>;
  if(key==='position')return m.position==null?'—':`#${value(m.position)}`;
  if(key==='sentiment')return <span className="pr-score-badge">{value(m.sentiment)}</span>;
  if(key==='visibilityRank')return m.visibilityRank==null?'—':`#${m.visibilityRank}`;
  if(key==='citationShare')return <span title="Share of citations among identified tracked-brand domains">{value(m.citationShare,'%')}</span>;
  if(key==='citationRank')return m.citationRank==null?'—':`#${m.citationRank}`;
  if(key==='topic')return <div className="pr-topic-tags"><button className="pr-topic-chip" onClick={()=>openEditor(p)} title="Edit topics">{p.topic}</button>{p.topics?.length>1&&<button className="pr-topic-more" onClick={()=>openEditor(p)} title={p.topics.slice(1).join(', ')}>+{p.topics.length-1}<ChevronDown size={11}/></button>}</div>;
  if(key==='type')return <button className={`pr-type ${p.type==='Branded'?'branded':''}`} title="Edit branded classification" onClick={()=>openEditor(p)}>{p.type==='Branded'?'Branded':'—'}<Pencil size={11}/></button>;
  if((key==='volume'||key==='difficulty')&&p.keywordData?.[key]!=null){const n=p.keywordData[key],level=key==='difficulty'?Math.ceil(n/20):n===0?0:n<100?1:n<1000?2:n<10000?3:n<100000?4:5;return <span className="pr-level-unavailable pr-level-measured" title={`${p.keywordData.source} · ${p.keywordData.measuredAt||'Date not supplied'} · ${p.keywordData.location||'Location not supplied'}`} aria-label={`${columnLabels[key]}: ${n}`} >{Array.from({length:5},(_,i)=><i key={i} className={i<level?'filled':''}/>)}<small>{n.toLocaleString()}{key==='difficulty'?'/100':' / mo'}</small></span>;}
  if(key==='volume'||key==='difficulty')return <button className="ai-text-button" title={`Import measured ${columnLabels[key].toLowerCase()} from a keyword provider. Missing data is not zero.`} disabled={busy||!!initial.error} onClick={()=>importRef.current?.click()}>Import data</button>;
  if(key==='mentions')return <button className="pr-logos" onClick={()=>setDetail(p)} title={m.brands.join(', ')||'No measured mentions'}>{m.brands.slice(0,4).map(name=><span key={name} title={name}><BrandLogo name={name} domain={domainFor(name)}/></span>)}{m.brands.length>4&&<span>+{m.brands.length-4}</span>}{!m.brands.length&&'—'}</button>;
  if(key==='coverage')return p.coverage?<span className="pr-coverage-result" title={`${p.coverage.reason} ${p.coverage.scope} · ${new Date(p.coverage.at).toLocaleDateString()}`}>{p.coverage.url?<a href={p.coverage.url} target="_blank" rel="noreferrer">{p.coverage.status}<ArrowUpRight size={12}/></a>:p.coverage.status}</span>:unavailable('Page coverage');
  if(key==='location')return m.latest?.location||'Not specified';
  if(key==='intent')return p.intent||'Custom';
  if(key==='created')return p.createdAt?new Date(p.createdAt).toLocaleDateString():'—';
  if(key==='tracked')return (p.trackedAt||m.history.at(-1)?.at)?new Date(p.trackedAt||m.history.at(-1).at).toLocaleDateString():'—';
  return unavailable(columnLabels[key]);
 }
 function row(p){const m=metrics(p);return <tr key={p.id} className={selection.has(p.id)?'pr-selected':''}><td><input type="checkbox" aria-label={`Select ${p.text}`} checked={selection.has(p.id)} onChange={e=>setSelection(prev=>{const next=new Set(prev);e.target.checked?next.add(p.id):next.delete(p.id);return next;})}/></td><td className="pr-question"><button title={p.text} onClick={()=>setDetail(p)}><span>{p.text}</span><ArrowUpRight size={14}/></button></td>{enabled.map(key=><td key={key}>{cell(p,m,key)}</td>)}<td><div className="pr-row-actions"><button className="cs-button" aria-label={`Edit ${p.text}`} disabled={busy} onClick={()=>openEditor(p)}><Pencil size={14}/></button>{status!=='Active'&&<button className="ai-text-button" disabled={busy||!!initial.error} onClick={()=>update([p],{status:'saved',tracking:true})}>{status==='Archived'?'Restore':'Activate'}</button>}</div></td></tr>;}
 function groupRow(t,list){const m=groupPromptMetrics(list,answers,business,days);return <tr className="pr-group"><td><button aria-label={`Toggle ${t}`} aria-expanded={!closed.has(t)} onClick={()=>setClosed(prev=>{const next=new Set(prev);next.has(t)?next.delete(t):next.add(t);return next;})}><ChevronDown size={13}/></button></td><td><div className="pr-group-title"><button onClick={()=>setDetail({id:`topic-${t}`,text:t,topic:t,groupPrompts:list})}><strong>{t}</strong></button><span>{list.length} prompts</span></div></td>{enabled.map(key=><td key={key}>{['visibility','position','sentiment'].includes(key)?<span className="pr-score-badge">{key==='position'?(m?.position==null?'—':`#${value(m.position)}`):value(m?.[key],key==='visibility'?'%':'')}</span>:null}</td>)}<td><button className="ai-text-button" onClick={()=>setDetail({id:`topic-${t}`,text:t,topic:t,groupPrompts:list})}>Analyze</button></td></tr>;}
 return <div className="ai-research pr-workspace">
 <div className="pr-heading"><div><h2>Prompts</h2><p>Understand the questions that shape your visibility.</p></div></div>
 <div className="pr-mode" role="group" aria-label="Prompt workspace">{['Your prompts','Prompt research'].map(name=><button key={name} aria-pressed={mode===name} onClick={()=>{setMode(name);setGroup(name==='Your prompts');setStatus(name==='Your prompts'?'Active':'Proposed');setSelection(new Set());setTopic('All topics');}}>{name}</button>)}<span><i/>{ready?'Selected collector ready':'Selected collector unavailable'}</span></div>
 {error&&<p className="air-error" role="alert">{error}</p>}{busy&&<p className="pr-progress" role="status">{progress} Keep this page open.</p>}
 <div className={`panel pr-shell ${mode==='Prompt research'?'with-topics':''}`}>
 {mode==='Prompt research'&&<aside className="pr-topics" aria-label="Research topics"><div><h3>Topics</h3><button className="cs-button" aria-label="Add topic" onClick={()=>setNewTopic('')}><Plus size={16}/></button></div>{newTopic!==null&&<form onSubmit={e=>{e.preventDefault();const t=newTopic.trim();if(t&&!topics.includes(t)){try{localStorage.setItem(storageKey+':topics',JSON.stringify([...extraTopics,t]));setExtraTopics([...extraTopics,t]);setTopic(t);setNewTopic(null);}catch{setError('Could not save topic.');}}}}><input aria-label="New topic name" maxLength={80} required value={newTopic} onChange={e=>setNewTopic(e.target.value)} placeholder="Topic name"/><button className="cs-button">Add</button><button type="button" className="ai-text-button" onClick={()=>setNewTopic(null)}>Cancel</button></form>}{['All topics',...topics].map(t=><button key={t} className="pr-topic-link" aria-pressed={topic===t} onClick={()=>{setTopic(t);setSelection(new Set());}}><span>{t}</span><span><b>{all.filter(p=>(t==='All topics'||(p.topics||[p.topic]).includes(t))&&statusOf(p)==='Active').length}</b><em>{all.filter(p=>(t==='All topics'||(p.topics||[p.topic]).includes(t))&&statusOf(p)==='Proposed').length}</em></span></button>)}<p>Active / Proposed</p></aside>}
 <section className="pr-main"><div className="pr-toolbar"><div className="pr-top-actions"><label className="pr-select"><select aria-label="Collection engine" value={collectionEngine} disabled={busy} onChange={e=>setCollectionEngine(e.target.value)}><option value="chatgpt">ChatGPT Search</option><option value="gemini">Gemini · availability varies</option><option value="claude-api">Claude API · web search</option><option value="perplexity-api">Perplexity Sonar</option></select></label><button className="cs-button" onClick={()=>openEditor() }><Plus size={16}/>Add prompts</button><button className="cs-button filled" disabled={busy||!collection?.analysisConfigured} onClick={research}><Sparkles size={16}/>{collection?.plan?'Explore suggestions':'Generate prompts & topics'}</button></div><label className="pr-select"><select aria-label="Group prompts" value={group?'topic':'none'} onChange={e=>setGroup(e.target.value==='topic')}><option value="topic">By topic</option><option value="none">All prompts</option></select></label><details className="pr-filters-menu"><summary>Filter <ChevronDown size={13}/></summary><div className="pr-filters"><label>Type<select value={type} onChange={e=>setType(e.target.value)}><option>All types</option><option>Branded</option><option>Unbranded</option></select></label><label>Intent<select value={intent} onChange={e=>setIntent(e.target.value)}>{['All intents','Discovery','Comparison','Buying decisions','Use cases','Custom'].map(i=><option key={i}>{i}</option>)}</select></label><label>Period<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option><option value={0}>All collected data</option></select></label><span>{all.filter(p=>statusOf(p)==='Active').length} active prompts · On-demand collection</span></div></details><details className="pr-popover"><summary><Columns3 size={15}/>Columns</summary><div>{Object.keys(columns).map(c=><label key={c}><input type="checkbox" checked={columns[c]} onChange={e=>setColumns({...columns,[c]:e.target.checked})}/>{columnLabels[c]}</label>)}</div></details><label className="pr-search"><Search size={15}/><input aria-label="Search prompts" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search prompts…"/></label><button className="cs-button" onClick={()=>{setClosed(closed.size?new Set():new Set(groups.map(([t])=>t)));}}>{closed.size?'Expand all':'Collapse all'}</button><button className="cs-button" onClick={exportResults} disabled={!visible.length}><Download size={15}/>Export</button></div>

 <div className="pr-status-tabs" role="group" aria-label="Prompt status">{['Active','Proposed','Archived'].map(s=><button key={s} aria-pressed={status===s} onClick={()=>{setStatus(s);setSelection(new Set());}}>{s}<span>{all.filter(p=>statusOf(p)===s).length}</span></button>)}<button className="ai-text-button" disabled={busy||!!initial.error} title="CSV columns: Prompt, Source, Volume, Difficulty, Date, Location. Use exact prompt text; difficulty is 0–100." onClick={()=>importRef.current?.click()}>Import keyword data</button><button className="ai-text-button" onClick={downloadKeywordTemplate} disabled={!visible.length}>Download import template</button><input ref={importRef} type="file" accept=".csv,text/csv" hidden onChange={importKeywords}/><button className="ai-text-button" onClick={()=>openEditor({bulk:true})}>Bulk add</button></div>
 {selected.length>0&&<div className="pr-bulk" role="region" aria-label="Selected prompt actions"><strong>{selected.length} selected</strong><button className="cs-button" disabled={busy||!collection?.analysisConfigured||selected.length>5} onClick={inspectCoverage}>Check page coverage{selected.length>5?' (max 5)':''}</button>{status!=='Active'&&<button className="cs-button" disabled={busy||!!initial.error} onClick={()=>update(selected,{status:'saved',tracking:true})}>Activate</button>}{status==='Active'&&<><button className="cs-button filled" disabled={busy||!ready||selected.length>5||remaining<selected.length} onClick={()=>collect(selected)}>Run selected{selected.length>5?' (max 5)':''}</button><button className="cs-button" disabled={busy} onClick={()=>update(selected,{tracking:false})}>Pause</button></>}<button className="cs-button" disabled={busy} onClick={()=>update(selected,{status:status==='Archived'?'saved':'archived',tracking:false})}>{status==='Archived'?'Restore to proposed':'Archive'}</button><button className="ai-text-button" onClick={()=>setSelection(new Set())}>Clear</button></div>}
 <p className="pr-caption pr-list-caption">{status==='Proposed'?'Review suggestions, then activate the questions you want to measure. AI-generated ideas are not search-volume estimates.':status==='Active'?'Select prompts to run a collection. Open any question for rankings, citations and response history.':'Archived prompts keep their evidence and can be restored.'}</p>
 <div className="ai-table-scroll pr-table-wrap" tabIndex={0} aria-label="Prompt performance table"><table className="pr-table" style={{minWidth:520+enabled.length*125}}><thead><tr><th><input type="checkbox" aria-label="Select all visible prompts" checked={!!visible.length&&visible.every(p=>selection.has(p.id))} onChange={e=>setSelection(e.target.checked?new Set(visible.map(p=>p.id)):new Set())}/></th><th><button onClick={()=>setSort({key:'text',asc:!sort.asc})}>Prompt<ChevronDown size={12}/></button></th>{enabled.map(key=><th key={key}><button onClick={()=>setSort({key,asc:sort.key===key?!sort.asc:true})}>{columnLabels[key]}<ChevronDown size={12}/></button></th>)}<th>Actions</th></tr></thead><tbody>{groups.map(([t,list])=><React.Fragment key={t}>{t&&groupRow(t,list)}{(!t||!closed.has(t))&&list.map(row)}</React.Fragment>)}</tbody></table></div>
 {!visible.length&&<div className="pr-empty"><FolderOpen size={28}/><h3>{status==='Active'?'Choose the prompts you want to track':'No prompts match this view'}</h3><p>{status==='Active'?'Open Prompt research, select questions and activate them.':'Adjust your filters or add a prompt to this topic.'}</p><button className="cs-button" onClick={()=>{setMode('Prompt research');setGroup(false);setStatus('Proposed');setTopic('All topics');setQuery('');setType('All types');setIntent('All intents');}}>Explore proposed prompts</button></div>}
 <ResearchFindings answers={answers} onOpen={a=>setDetail(all.find(p=>normalizePrompt(p.text)===normalizePrompt(a.prompt))||{id:a.id,text:a.prompt,topic:a.topic,type:a.type})}/>
 <PromptSchedule collection={collection} selected={selected} busy={busy} onSave={schedulePrompts}/><footer className="pr-footer"><span>{visible.length} prompts · {new Set(visible.flatMap(p=>p.topics||[p.topic])).size} topics</span><details><summary>Collection details</summary><p>{collection?.attemptsRemaining??'—'} trial attempts remaining. Selected engine · Location unspecified. One collection per question, engine and UTC day; subsequent requests reuse today’s result. Daily and weekly schedules are available below the table. Keyword data can be imported from a provider CSV: Prompt, Source, Volume, Difficulty (0–100), Date (YYYY-MM-DD), Location. Exact prompt matches only; missing values stay empty. Prompts and answers share the connected server store. An offline library copy stays in this browser.</p><button className="ai-text-button" onClick={onSettings}>Manage connectors</button></details></footer>
 </section></div>
 {editor&&<dialog ref={editorRef} className="pr-editor" aria-labelledby="pr-editor-title" onCancel={()=>setEditor(null)}><form onSubmit={submit}><header><h3 id="pr-editor-title">{editor.id?'Edit prompt':editor.bulk?'Bulk add prompts':'Add prompts'}</h3><button type="button" className="cs-button" aria-label="Close editor" onClick={()=>setEditor(null)}><X size={16}/></button></header><label>Prompt{!editor.id&&'s'}<textarea required rows={5} maxLength={editor.id?500:50100} value={editor.text} onChange={e=>setEditor({...editor,text:e.target.value})} placeholder="One question per line"/></label><p className="pr-caption">{editor.id?'Changing the question keeps old answer evidence separate.':'Paste up to 100 prompts, one per line. Duplicate questions are skipped.'}</p><label>Topics (comma-separated)<input list="pr-topic-list" maxLength={320} value={editor.topic} onChange={e=>setEditor({...editor,topic:e.target.value})}/></label><datalist id="pr-topic-list">{topics.map(t=><option key={t}>{t}</option>)}</datalist><label>Type<select value={editor.type} onChange={e=>setEditor({...editor,type:e.target.value})}><option>Unbranded</option><option>Branded</option></select></label><label className="pr-check"><input type="checkbox" checked={!!editor.tracking} onChange={e=>setEditor({...editor,tracking:e.target.checked})}/>Activate for on-demand tracking</label>{error&&<p role="alert">{error}</p>}<button className="cs-button filled" disabled={busy||!!initial.error}>Save prompts</button></form></dialog>}
 {detail&&<PromptDetail prompt={all.find(p=>p.id===detail.id)||detail} metrics={detail.groupPrompts?{...groupPromptMetrics(detail.groupPrompts,answers,business,days),history:answers.filter(a=>detail.groupPrompts.some(p=>normalizePrompt(p.text)===normalizePrompt(a.prompt))&&(days===0||new Date(a.at)>=new Date(Date.now()-days*86400000)))}:metrics(detail)} business={business} domainFor={domainFor} onClose={()=>setDetail(null)} onRun={p=>collect([p])} busy={busy} canRun={!detail.groupPrompts&&ready&&remaining>0}/>}
 </div>;
}
