import React,{useEffect,useState} from 'react';
import {ArrowUpRight,Globe2,RefreshCw} from 'lucide-react';
import {aiFetch} from './ai-cloud';
import './ai-traffic.css';

export function AiTraffic({business,onSettings}){
 const [data,setData]=useState(null),[report,setReport]=useState(null),[ga4,setGa4]=useState(''),[gsc,setGsc]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function call(action,extra={}){const response=await aiFetch('/api/ai/searchapi',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,business:{name:business.name,domain:business.domain},...extra})});const json=await response.json();if(!response.ok)throw Error(json.error||'Unable to read traffic data.');return json;}
 useEffect(()=>{let active=true;setData(null);setReport(null);call('list').then(result=>{if(active){setData(result);setGa4(result.googleProperties?.ga4PropertyId||'');setGsc(result.googleProperties?.gscSiteUrl||'');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[business.domain]);
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const result=await call('googleProperties',{properties:{ga4PropertyId:ga4,gscSiteUrl:gsc}});setData(result);setReport(null);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function load(){setBusy(true);setError('');try{const result=await call('trafficReport');setData(result);setReport(result.traffic);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const properties=data?.googleProperties||{},connected=!!(properties.ga4PropertyId||properties.gscSiteUrl);
 return <div className="ait-root"><div className="cs-page-intro"><div><h2>AI traffic &amp; search performance</h2><p>Measure visits from known AI referrers and the Google queries that reach your website.</p></div>{connected&&<button className="cs-button filled" disabled={busy||!data?.googleTrafficConfigured} onClick={load}><RefreshCw size={15}/>{busy?'Loading…':'Load latest reports'}</button>}</div>
  {error&&<p role="alert" className="aow-error">{error}</p>}
  <section className="panel ait-setup"><div className="ait-setup-head"><Globe2 size={20}/><div><h3>{connected?'Property connection':'Connect website analytics'}</h3><p>{business.name} · {business.domain}</p></div></div><p>GA4 and Search Console need properties you own and a read-only service account. Create or select properties for this business, grant the service account read access, then load real reports.</p><form onSubmit={save}><label>GA4 numeric property ID<input inputMode="numeric" pattern="[0-9]{4,20}" value={ga4} onChange={e=>setGa4(e.target.value)} placeholder="123456789"/></label><label>Search Console property<input value={gsc} onChange={e=>setGsc(e.target.value)} placeholder={`sc-domain:${business.domain}`}/></label><button className="cs-button" disabled={busy||!data}>Save properties</button></form><p className="ait-service">{data?.googleTrafficConfigured?<>Grant <strong>{data.googleServiceAccount}</strong> read access to each property, then load reports.</>:'The server-only Google service account has not been configured yet. Property IDs alone do not grant access.'}</p><div className="ait-links"><a href="https://analytics.google.com/analytics/web/" target="_blank" rel="noreferrer">Open GA4<ArrowUpRight size={13}/></a><a href="https://search.google.com/search-console" target="_blank" rel="noreferrer">Open Search Console<ArrowUpRight size={13}/></a><button className="ai-text-button" onClick={onSettings}>Connection status<ArrowUpRight size={13}/></button></div></section>
  {report&&<><div className="ait-stats"><section className="panel"><span>AI referral sessions</span><strong>{report.ga4?.visits?.toLocaleString()??'—'}</strong><small>GA4 · last 30 complete days</small></section><section className="panel"><span>AI sources</span><strong>{report.ga4?.engines?.length??'—'}</strong><small>Known referring domains</small></section><section className="panel"><span>Search Console queries</span><strong>{report.gsc?.length??'—'}</strong><small>Top reported query/page rows</small></section></div>{Object.entries(report.errors||{}).map(([source,message])=><p className="aow-error" key={source}>{source.toUpperCase()}: {message}</p>)}<div className="ait-grid"><section className="panel"><h3>Visits by AI referrer</h3>{report.ga4?.engines?.length?<div className="ai-bars">{report.ga4.engines.map((row,i)=><div key={row.name}><div><span>{row.name}</span><strong>{row.visits.toLocaleString()}</strong></div><div className="ai-track"><i className={`ai-color-${i%4}`} style={{width:`${row.visits/report.ga4.visits*100}%`}}/></div></div>)}</div>:<p>No visits from recognized AI referrer domains in this report.</p>}</section><section className="panel"><h3>Top AI landing pages</h3>{report.ga4?.pages?.length?<div className="ai-table-scroll"><table><thead><tr><th>Page</th><th>Sessions</th></tr></thead><tbody>{report.ga4.pages.slice(0,10).map(p=><tr key={p.path}><td>{p.path}</td><td>{p.visits.toLocaleString()}</td></tr>)}</tbody></table></div>:<p>No matching landing pages yet.</p>}</section></div><section className="panel ait-search"><h3>Google Search Console</h3><p>Organic Google search performance, separate from AI-answer recommendations.</p>{report.gsc?.length?<div className="ai-table-scroll"><table><thead><tr><th>Query</th><th>Page</th><th>Clicks</th><th>Impressions</th><th>Position</th></tr></thead><tbody>{report.gsc.slice(0,30).map((r,i)=><tr key={`${r.query}-${r.page}-${i}`}><td>{r.query}</td><td>{r.page}</td><td>{r.clicks.toLocaleString()}</td><td>{r.impressions.toLocaleString()}</td><td>{r.position.toFixed(1)}</td></tr>)}</tbody></table></div>:<p>No Search Console rows returned.</p>}</section></>}
  <p className="ait-note">Known referrer domains identify some visits from AI tools. They do not reveal the exact prompt or prove that a particular answer caused a visit. Google AI Overview clicks may appear as ordinary Google traffic. Search Console reports only the top available rows.</p>
 </div>;
}
