import React, { useRef, useState } from "react";
import { Sparkles, Search, Plus, Check, ArrowUpRight, FileText, Globe2 } from "lucide-react";
import "./ai-workspace.css";
import { AiInsights } from "./AiInsights";
import { AiPromptResearch } from "./AiPromptResearch";
import { AiOpportunityWorkflow } from "./AiOpportunityWorkflow";
import { AiTraffic } from "./AiTraffic";

const tabs=["Overview","Citation Tracker","Share of Voice","Content Scorecard","AI Opportunities","Keyword Discovery","Content Gaps","AI Traffic","Prompt research & tracking","AI Insights"];
const groups=[{name:"AI Insights",tabs:[9]},{name:"Research",tabs:[8,5]},{name:"Evidence",tabs:[1,2,0]},{name:"Improve",tabs:[4,3,6]},{name:"Traffic",tabs:[7]}];
const prompts=[['What does Uplift AI do?','Brand answer',true],['How can a small business automate SEO?','Discovery prompt',true],['Which tools track AI search visibility?','Discovery prompt',false],['How do I get my brand cited by ChatGPT?','Discovery prompt',false],['What is generative engine optimization?','Discovery prompt',false],['Can Uplift AI create a content calendar?','Brand answer',true]];
const terms=[['AI SEO automation',1900,'Medium'],['AI search visibility',1300,'Easy'],['generative engine optimization',2400,'Medium'],['automated content publishing',720,'Easy'],['Google Business Profile SEO',880,'Easy'],['AI citation tracking',590,'Easy'],['SEO content calendar',1600,'Medium'],['technical SEO checklist',2900,'Medium'],['small business SEO software',1200,'Medium'],['AI content optimization',1000,'Easy'],['local SEO automation',480,'Easy'],['content gap analysis',2100,'Medium']].map(([term,volume,difficulty],id)=>({id,term,volume,difficulty,planned:id<8}));
const articles=[['A practical guide to AI search visibility',88],['Build an SEO content calendar that keeps moving',86],['What makes a brand worth citing in ChatGPT?',84],['Your technical SEO audit checklist',90],['Keyword research for small business growth',87],['Turn one idea into a week of social content',83],['Google Business Profile optimization, step by step',80],['How internal linking connects your content',88]];
const engines=[['ChatGPT',44],['Perplexity',39],['Google AI',35],['Claude',18],['Gemini',9]];
function Tag({children,green=false}){return <span className={`ai-tag ${green?'green':''}`}>{children}</span>;}
function Heading({title,description,children}){return <div className="cs-page-intro"><div><h2>{title}</h2><p>{description}</p></div>{children}</div>;}
function Panel({title,children,className=''}){return <section className={`panel ai-panel ${className}`}><h3>{title}</h3>{children}</section>;}
function Bars({rows,max=100,suffix='%'}){return <div className="ai-bars">{rows.map(([label,value],i)=><div key={label}><div><span>{label}</span><strong>{value.toLocaleString()}{suffix}</strong></div><div className="ai-track"><i className={`ai-color-${i%4}`} style={{width:`${value/max*100}%`}}/></div></div>)}</div>;}
function Table({headers,children}){return <div className="ai-table-scroll" tabIndex={0} aria-label="Scrollable report"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;}
function Trend({traffic=false}) {
 const values=traffic?[420,570,610,805,940,1363]:[7,9,11,12,15,18];
 const max=Math.max(...values), min=Math.min(...values);
 const points=values.map((value,i)=>({x:15+i*114,y:155-(value-min)/(max-min)*130,value}));
 return <div className="ai-trend" role="img" aria-label={`Illustrative ${traffic?'weekly referral visits':'share of voice'}: ${values.join(', ')}`}><svg viewBox="0 0 600 180"><polyline points={points.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="3"/>{points.map((p,i)=><g key={i}><circle cx={p.x} cy={p.y} r="5"/><text x={p.x} y={p.y-16} textAnchor={i===0?'start':i===5?'end':'middle'}>{p.value}{traffic?'':'%'}</text></g>)}</svg><div>{(traffic?['W1','W2','W3','W4','W5','W6']:['Apr','May','Jun','Jul','Aug','Sep']).map(t=><span key={t}>{t}</span>)}</div></div>;
}

export function AiWorkspace({overview,onToast,onCreate,onSettings,business}){
 const [tab,setTab]=useState(9),[evidence,setEvidence]=useState(null),[review,setReview]=useState(null),[search,setSearch]=useState(''),[promptFilter,setPromptFilter]=useState('All prompts'),[adding,setAdding]=useState(false),[newTerm,setNewTerm]=useState('');
 const refs=useRef([]), groupRefs=useRef([]);
 const groupIndex=groups.findIndex(g=>g.tabs.includes(tab));
 const activeGroup=groups[groupIndex];
 const [keywords,setKeywords]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem('d2-ai-keywords'));return Array.isArray(saved)&&saved.every(k=>typeof k.term==='string'&&Number.isFinite(k.volume))?saved:terms;}catch{return terms;}});
 function save(next){setKeywords(next);try{localStorage.setItem('d2-ai-keywords',JSON.stringify(next));onToast('Keyword plan saved on this device.');}catch{onToast('Keyword plan updated for this session.');}}
 const gaps=prompts.filter(p=>!p[2]);
 return <section className={tab===0?'ai-overview-shell':'cs-page ai-workspace'}>
  <div className="ai-tabs" role="tablist" aria-label="AI visibility sections">{groups.map((group,i)=><button key={group.name} ref={el=>groupRefs.current[i]=el} id={`ai-group-${i}`} role="tab" aria-controls="ai-group-panel" aria-selected={groupIndex===i} tabIndex={groupIndex===i?0:-1} onClick={()=>setTab(group.tabs[0])} onKeyDown={e=>{const n=e.key==='ArrowRight'?(i+1)%groups.length:e.key==='ArrowLeft'?(i+groups.length-1)%groups.length:e.key==='Home'?0:e.key==='End'?groups.length-1:null;if(n!==null){e.preventDefault();setTab(groups[n].tabs[0]);groupRefs.current[n].focus();}}}>{group.name}</button>)}</div>
  <div id="ai-group-panel" role="tabpanel" aria-labelledby={`ai-group-${groupIndex}`}>
  {activeGroup.tabs.length>1&&<div className="ai-subtabs" role="tablist" aria-label={`${activeGroup.name} views`}>{activeGroup.tabs.map((i,pos)=><button key={i} ref={el=>refs.current[i]=el} id={`ai-tab-${i}`} role="tab" aria-controls="ai-panel" aria-selected={tab===i} tabIndex={tab===i?0:-1} onClick={()=>setTab(i)} onKeyDown={e=>{const n=e.key==='ArrowRight'?(pos+1)%activeGroup.tabs.length:e.key==='ArrowLeft'?(pos+activeGroup.tabs.length-1)%activeGroup.tabs.length:e.key==='Home'?0:e.key==='End'?activeGroup.tabs.length-1:null;if(n!==null){e.preventDefault();setTab(activeGroup.tabs[n]);refs.current[activeGroup.tabs[n]].focus();}}}>{tabs[i]}</button>)}</div>}
  <div id="ai-panel" role="tabpanel" aria-labelledby={activeGroup.tabs.length > 1 ? `ai-tab-${tab}` : `ai-group-${groupIndex}`}>
  {tab===9&&<AiInsights business={business} onSettings={onSettings} onResearch={()=>setTab(8)} onImprove={()=>setTab(4)}/>}
  {![9,8,3,4,6,7].includes(tab)&&<p className="aiv-data-notice">Existing Uplift AI demo tools · Illustrative examples, not measurements for {business.name}.</p>}
  {tab===8&&<AiPromptResearch business={business} onToast={onToast} onSettings={onSettings}/>}
  {tab===0&&overview}
  {tab===1&&<><Heading title="See where your brand becomes the answer." description="Inspect the questions, citations, and gaps behind your AI visibility."/><div className="ai-citation-layout"><Panel title="Citation coverage"><div className="ai-coverage"><div className="ai-dot-matrix" aria-label="45 percent citation coverage">{Array.from({length:100},(_,i)=><i className={i<45?'filled':''} key={i}/>)}</div><div><strong>45<small>%</small></strong><p>of tracked prompts cite your brand</p><Tag green>24 citations · sample</Tag></div></div><div className="ai-panel-foot">53 tracked prompts · All values illustrative</div></Panel><Panel title="Visibility over time"><Trend/><div className="ai-panel-foot">Share of voice · Illustrative monthly trend</div></Panel></div><Panel title="Prompt evidence"><div className="ai-filter-row">{['All prompts','Brand cited','Not cited'].map(f=><button className="cs-button" aria-pressed={promptFilter===f} key={f} onClick={()=>setPromptFilter(f)}>{f}</button>)}</div><Table headers={['Question','Prompt type','Result','AI engines','Evidence']}>{prompts.filter(p=>promptFilter==='All prompts'||p[2]===(promptFilter==='Brand cited')).map(p=><tr key={p[0]}><td>{p[0]}</td><td>{p[1]}</td><td><Tag green={p[2]}>{p[2]?'Brand cited':'Not cited'}</Tag></td><td>ChatGPT · Gemini</td><td><button className="ai-text-button" onClick={()=>setEvidence(p)}>View evidence<ArrowUpRight size={14}/></button></td></tr>)}</Table>{evidence&&<div className="ai-evidence" role="region" aria-label="Prompt evidence details"><div><h3>{evidence[0]}</h3><button className="cs-button" onClick={()=>setEvidence(null)}>Close evidence</button></div><p>{evidence[1]} · {evidence[2]?'Brand cited':'Not cited'} · ChatGPT & Gemini</p><p>Illustrative evidence only. A verified result would include the AI response, cited URLs, and scan timestamp. No live scan has been run.</p></div>}</Panel></>}
  {tab===2&&<><Heading title="Find your place in the conversation." description="Compare visibility across engines and see how your share changes."/><div className="ai-split"><Panel title="Competitive landscape"><div className="ai-rank-labels"><span>Brand</span><span>Share of voice</span></div>{[['Comparison brand A',26,35,'+2.1%'],['Comparison brand B',21,28,'+0.8%'],['Uplift AI',18,24,'+4.2%'],['Comparison brand C',14,19,'−1.2%']].map(([name,value,citations,change])=><div className={`ai-ranking ${name==='Uplift AI'?'highlight':''}`} key={name}><div><strong>{name}</strong><span>{citations} citations <em>{change}</em></span></div><div className="ai-ranking-bar"><i style={{width:`${value/30*100}%`}}/><b>{value}%</b></div></div>)}<p className="ai-panel-foot">Comparison brands and values are illustrative.</p></Panel><Panel title="Visibility by engine"><Bars rows={engines}/></Panel></div><Panel title="Share of voice over time" className="ai-wide-trend"><Trend/><p className="ai-panel-foot">18% in September · +4.2 percentage points in the sample reporting period</p></Panel></>}
  {tab===3&&<AiOpportunityWorkflow business={business} mode="scorecard" onCreate={onCreate} onResearch={()=>setTab(8)}/>}
  {tab===4&&<AiOpportunityWorkflow business={business} onCreate={onCreate} onResearch={()=>setTab(8)}/>}
  {tab===5&&<><Heading title="Discover the questions worth answering." description="Explore sample search demand and build your next content plan."><button className="cs-button filled" onClick={()=>setAdding(!adding)}><Plus size={15}/>Add keyword</button></Heading><div className="ai-keyword-summary"><span><strong>{keywords.length}</strong> keyword ideas</span><span><strong>{keywords.filter(k=>k.planned).length}</strong> in your plan</span><span><strong>{keywords.filter(k=>k.difficulty==='Easy').length}</strong> lower-difficulty ideas</span></div>{adding&&<form className="panel ai-add-form" onSubmit={e=>{e.preventDefault();const term=newTerm.trim();if(!term)return;if(keywords.some(k=>k.term.toLowerCase()===term.toLowerCase())){onToast('That keyword is already in your list.');return;}save([...keywords,{id:Date.now(),term,volume:0,difficulty:'Not assessed',planned:false}]);setNewTerm('');setAdding(false);}}><label>Keyword<input required maxLength={160} value={newTerm} onChange={e=>setNewTerm(e.target.value)} placeholder="What does your audience ask?"/></label><button className="cs-button filled">Save keyword</button><button type="button" className="cs-button" onClick={()=>setAdding(false)}>Cancel</button></form>}<Panel title="Keyword discovery"><label className="ai-search"><Search size={17}/><input aria-label="Search keyword ideas" placeholder="Find a keyword…" value={search} onChange={e=>setSearch(e.target.value)}/></label><Table headers={['Keyword','Monthly searches','Difficulty','Content plan']}>{keywords.filter(k=>k.term.toLowerCase().includes(search.toLowerCase())).map(k=><tr key={k.id}><td>{k.term}</td><td>{k.volume?k.volume.toLocaleString():'Not assessed'}</td><td><Tag green={k.difficulty==='Easy'}>{k.difficulty}</Tag></td><td>{k.planned?<span className="ai-planned"><Check size={15}/>In your plan</span>:<button className="ai-text-button" onClick={()=>save(keywords.map(v=>v.id===k.id?{...v,planned:true}:v))}>Add to plan<Plus size={15}/></button>}</td></tr>)}</Table>{!keywords.some(k=>k.term.toLowerCase().includes(search.toLowerCase()))&&<p className="ai-empty">No matching keywords. Try a broader search.</p>}</Panel></>}
  {tab===6&&<AiOpportunityWorkflow business={business} mode="gaps" onCreate={onCreate} onResearch={()=>setTab(8)}/>}
  {tab===7&&<AiTraffic business={business} onSettings={onSettings}/>}
  </div></div>{![0,8,9,3,4,6,7].includes(tab)&&<footer className="ai-footer">Illustrative Uplift AI dataset · September 2026<span>No live scans or analytics connection · Plans stay on this device</span></footer>}
 </section>;
}
