import React, {useState, useRef} from 'react';
import {Building2, Search, Sparkles, FileText, UserRound, ChartNoAxesColumn, Pencil, Check, X, Plus, Trash2, ArrowUpRight, MapPin, RefreshCw, CalendarDays, Upload, Image, Globe2, ShieldCheck} from 'lucide-react';
import {businessProfileSeed, brandColors} from './business-profile-data';
import './business-profile.css';
const STORE='dashboard-2-business-profile-v1';
const SOURCE='https://dashboard.upliftai.co/dashboard/business-settings';
const MAP='https://maps.google.com/?cid=2763697866273943626';
const tabs=[['Business Information',Building2],['SEO Keywords',Search],['Competitive Edge',Sparkles],['Content Settings',FileText],['Author Profile',UserRound],['Ranking & Analysis',ChartNoAxesColumn]];
const week=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
const locales={"en-US": "English (United States) (American English)", "en-CA": "English (Canada) (Canadian English)", "en-GB": "English (United Kingdom) (British English)", "en-AU": "English (Australia) (Australian English)", "fr-CA": "Fran\u00e7ais (Canada) (Canadian French)", "fr-FR": "Fran\u00e7ais (France) (European French)", "es-ES": "Espa\u00f1ol (Espa\u00f1a) (European Spanish)", "es-MX": "Espa\u00f1ol (M\u00e9xico) (Mexican Spanish)", "es-AR": "Espa\u00f1ol (Argentina) (Argentine Spanish)", "de-DE": "Deutsch (Deutschland) (Standard German)", "zh-CN": "\u4e2d\u6587 (\u7b80\u4f53) (Simplified Chinese)", "ja-JP": "\u65e5\u672c\u8a9e (Standard Japanese)", "pt-BR": "Portugu\u00eas (Brasil) (Brazilian Portuguese)", "pt-PT": "Portugu\u00eas (Portugal) (European Portuguese)", "it-IT": "Italiano (Italia) (Standard Italian)", "ru-RU": "\u0420\u0443\u0441\u0441\u043a\u0438\u0439 (\u0420\u043e\u0441\u0441\u0438\u044f) (Standard Russian)", "ar-SA": "\u0627\u0644\u0639\u0631\u0628\u064a\u0629 (\u0627\u0644\u0633\u0639\u0648\u062f\u064a\u0629) (Standard Arabic)", "hi-IN": "\u0939\u093f\u0928\u094d\u0926\u0940 (\u092d\u093e\u0930\u0924) (Standard Hindi)", "nl-NL": "Nederlands (Nederland) (Standard Dutch)", "ko-KR": "\ud55c\uad6d\uc5b4 (\ub300\ud55c\ubbfc\uad6d) (Standard Korean)"};
function readProfile(){try{return {...businessProfileSeed,...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return businessProfileSeed}}
function Button({children,primary=false,...props}){return <button className={'cs-button '+(primary?'filled':'')} {...props}>{children}</button>}
function SourceLink({children}){return <a className="cs-button" href={SOURCE} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={16}/></a>}
function Panel({title,description,action,children,className=''}){return <section className={'panel bp-panel '+className}><div className="bp-heading"><div><h3>{title}</h3>{description&&<p>{description}</p>}</div>{action}</div>{children}</section>}
function EditPanel({title,description,fields,profile,onSave,children}){
 const [editing,setEditing]=useState(false);const [draft,setDraft]=useState({});
 return <Panel title={title} description={description} action={!editing&&<Button aria-label={'Edit '+title} onClick={()=>{setDraft(profile);setEditing(true)}}><Pencil size={15}/>Edit</Button>}>
 {editing?<form onSubmit={e=>{e.preventDefault();if(onSave(Object.fromEntries(fields.map(f=>[f.key,draft[f.key]]))))setEditing(false)}}><div className="bp-form-grid">{fields.map(f=><label key={f.key} className={f.multiline?'bp-wide':''}>{f.label}{f.multiline?<textarea rows={f.rows||5} maxLength={f.maxLength} value={draft[f.key]||''} onChange={e=>setDraft({...draft,[f.key]:e.target.value})}/>:<input type={f.type||'text'} required={f.required} maxLength={f.maxLength} value={draft[f.key]||''} onChange={e=>setDraft({...draft,[f.key]:e.target.value})}/>}</label>)}</div><div className="bp-form-actions"><span>Saved only in this browser.</span><Button type="button" onClick={()=>setEditing(false)}>Cancel</Button><Button primary type="submit"><Check size={16}/>Save changes</Button></div></form>:children}
 </Panel>
}
function Details({entries}){return <dl className="bp-details">{entries.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||<span className="bp-muted">Not set</span>}</dd></div>)}</dl>}
export function BusinessProfile({onToast}){
 const [profile,setProfile]=useState(readProfile);const [active,setActive]=useState(0);const [query,setQuery]=useState('');const [keyword,setKeyword]=useState('');const [priority,setPriority]=useState('Must Have');const [newCompetitor,setNewCompetitor]=useState('');const [competitorName,setCompetitorName]=useState('');const [editingKeyword,setEditingKeyword]=useState(null);const [keywordDraft,setKeywordDraft]=useState('');const [locale,setLocale]=useState(profile.locale);
 const profileRef=useRef(profile);
 const save=patch=>{const current=profileRef.current;const next={...current,...(typeof patch==='function'?patch(current):patch)};try{localStorage.setItem(STORE,JSON.stringify(next));profileRef.current=next;setProfile(next);onToast('Business profile saved in this browser.');return true}catch{onToast('Could not save. Browser storage is full or unavailable. Try a smaller image.');return false}};
 const upload=async(e,key)=>{
  const f=e.target.files?.[0];e.target.value='';if(!f)return;
  const isAuthor=key==='authorImage';
  const types=isAuthor?['image/png','image/jpeg','image/webp']:['image/png','image/jpeg','image/webp','image/gif','image/svg+xml'];
  if(!types.includes(f.type)||f.size>(isAuthor?1:8)*1024*1024){onToast(isAuthor?'Choose a JPEG, PNG, or WebP headshot under 1 MB.':'Choose a PNG, JPEG, WebP, GIF, or SVG image under 8 MB.');return}
  const objectUrl=URL.createObjectURL(f);
  try{
   const bitmap=await new Promise((resolve,reject)=>{const img=new window.Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=objectUrl});
   if(isAuthor&&(bitmap.naturalWidth<256||bitmap.naturalHeight<256)){onToast('Choose an author image at least 256 × 256 pixels.');return}
   const scale=Math.min(1,1200/Math.max(bitmap.naturalWidth,bitmap.naturalHeight));
   const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.naturalWidth*scale));canvas.height=Math.max(1,Math.round(bitmap.naturalHeight*scale));
   canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);
   const data=canvas.toDataURL('image/webp',0.75);
   save(current=>key==='images'?{images:[...current.images,{name:f.name,data}]}:{[key]:data});
  }catch{onToast('This image could not be read. Please try another file.')}finally{URL.revokeObjectURL(objectUrl)}
 };
 const uploader=(key,label)=> <label className="cs-button bp-upload"><Upload size={15}/>{label}<input type="file" accept={key==='authorImage'?'image/png,image/jpeg,image/webp':'image/png,image/jpeg,image/webp,image/gif,image/svg+xml'} aria-label={label} onChange={e=>upload(e,key)}/></label>;
 const brandPanel = (<Panel className="bp-brand-panel" title="Brand identity" description="LunchLink’s original brand context."><div className="bp-brand-preview">{profile.logo?<img src={profile.logo} alt="LunchLink brand logo"/>:<><span className="bp-brand-initial">L.</span><strong>LunchLink</strong></>}</div>{uploader('logo','Replace logo')}<p className="bp-muted bp-space">Local logo preview · up to 8 MB, optimized for storage</p><div className="bp-favicon"><span>{profile.favicon?<img src={profile.favicon} alt="Favicon preview"/>:"L."}</span>{uploader('favicon','Replace favicon')}</div><h4>Primary colors</h4><div className="bp-palette primary">{brandColors.slice(0,2).map(color=><div key={color}><i style={{background:color}}/><span>{color}</span></div>)}</div><h4>Secondary colors</h4><div className="bp-palette">{brandColors.slice(2).map(color=><div key={color}><i style={{background:color}}/><span>{color}</span></div>)}</div><div className="bp-brand-font"><span>Aa</span><div><small>Original brand font</small><strong>GeistSans</strong></div></div><p className="bp-muted">Last analyzed · Aug 18, 2026</p><SourceLink>Re-analyze brand in Uplift</SourceLink></Panel>);
 const refreshPanel = (<div className="bp-refresh"><CalendarDays size={24}/><h3>Keep your context fresh.</h3><p>Uplift re-reads your website and connected sources each month.</p><div><span>Next source refresh</span><strong>September 25, 2026</strong></div><SourceLink><RefreshCw size={15}/>Refresh in Uplift</SourceLink></div>);
 const shownKeywords=profile.keywords.filter(k=>k.text.toLowerCase().includes(query.toLowerCase()));
 return <section className="business-profile cs-page">
  <div className="cs-page-intro"><div><h2>A little context. Better content.</h2><p>Your business, your voice, and everything that makes it yours.</p></div><a href={profile.website} target="_blank" rel="noreferrer" className="cs-button">Visit website<ArrowUpRight size={17}/></a></div>
  <div className="bp-overview">
   {[{label:'Business profile',value:profile.name,note:profile.type,icon:Building2,tab:0,tone:'blue'}, {label:'Content direction',value:profile.keywords.length,note:'Keywords in your strategy',icon:Search,tab:1,tone:'purple'}, {label:'Competitive landscape',value:profile.competitors.length,note:'Businesses in your comparison',icon:Globe2,tab:2,tone:'green'}, {label:'Publishing rhythm',value:profile.frequency,note:`${profile.days.length} active days each week`,icon:CalendarDays,tab:3,tone:'gold'}].map(({label,value,note,icon:Icon,tab,tone})=><button className={'panel bp-overview-card '+tone} key={label} onClick={()=>setActive(tab)}><span className="bp-overview-title">{label}<span className="metric-icon"><Icon size={18}/></span></span><strong>{value}</strong><span className="bp-overview-note">{note}<ArrowUpRight size={17}/></span></button>)}
  </div>
  <div className="bp-tabs" role="tablist" aria-label="Business profile sections">{tabs.map(([name,Icon],i)=><button type="button" role="tab" aria-selected={active===i} aria-controls={'bp-panel-'+i} id={'bp-tab-'+i} tabIndex={active===i?0:-1} key={name} onClick={()=>setActive(i)} onKeyDown={e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();setActive(next);document.getElementById('bp-tab-'+next)?.focus()}}}><Icon size={17}/>{name}</button>)}</div>
  <div className={"bp-layout bp-view-"+active}><div role="tabpanel" id={'bp-panel-'+active} aria-labelledby={'bp-tab-'+active} className="bp-main">
  {active===0&&<>
   <EditPanel title="Business information" description="The essentials behind every piece of content." profile={profile} onSave={save} fields={[{key:'name',label:'Business name',required:true},{key:'type',label:'Business type',required:true},{key:'phone',label:'Mobile number',type:'tel'}]}><Details entries={[["Business name",profile.name],["Business type",profile.type],["Website",<a href={profile.website} target="_blank" rel="noreferrer">{profile.website}<ArrowUpRight size={14}/></a>],["Email",profile.email],["Mobile number",profile.phone]]}/></EditPanel>
   <EditPanel title="About the business" profile={profile} onSave={save} fields={[{key:'about',label:'About the business',multiline:true,rows:7}]}><p className="bp-prose">{profile.about}</p></EditPanel>
   <EditPanel title="Location & service area" description="Where your business is based, and who you serve." profile={profile} onSave={save} fields={[{key:'address',label:'Address'},{key:'city',label:'City'},{key:'province',label:'State / province'},{key:'country',label:'Country'},{key:'area',label:'Service area'},{key:'locations',label:'Service locations'}]}><div className="bp-location"><div className="bp-place"><MapPin size={24}/><div><strong>{profile.city}</strong><span>{profile.locations}</span></div></div><Details entries={[["Address",profile.address],["State / province",profile.province],["Country",profile.country],["Service area",profile.area]]}/></div><div className="bp-foot"><span><ShieldCheck size={17}/>Source profile: verified on Google Maps · 90/100</span><a href={MAP} target="_blank" rel="noreferrer">View on Google Maps<ArrowUpRight size={15}/></a></div><p className="bp-muted">Verification reflects the source snapshot. Edited addresses need verification in Uplift AI.</p><div className="bp-space"><SourceLink>Verify on Google in Uplift</SourceLink></div></EditPanel>
   {brandPanel}
   {refreshPanel}
  </>}
  {active===1&&<Panel title="SEO keywords" description="The language your next customers are searching for.">
   <form className="bp-add" onSubmit={e=>{e.preventDefault();const text=keyword.trim();if(!text)return;if(profile.keywords.some(k=>k.text.toLowerCase()===text.toLowerCase())){onToast('This keyword is already in your profile.');return}if(save({keywords:[...profile.keywords,{id:crypto.randomUUID(),text,priority}]}))setKeyword('')}}><label>New keyword<input required placeholder="Add a phrase to your content strategy" value={keyword} onChange={e=>setKeyword(e.target.value)}/></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option>Must Have</option><option>Nice to Have</option></select></label><Button primary type="submit"><Plus size={16}/>Add keyword</Button></form>
   <label className="bp-search"><Search size={18}/><input aria-label="Search profile keywords" placeholder="Find a keyword…" value={query} onChange={e=>setQuery(e.target.value)}/></label>
   <div className="bp-keywords">{shownKeywords.map(k=><div className="bp-keyword" key={k.id}>{editingKeyword===k.id?<form className="bp-inline-edit" onSubmit={e=>{e.preventDefault();const text=keywordDraft.trim();if(!text)return;if(profile.keywords.some(x=>x.id!==k.id&&x.text.toLowerCase()===text.toLowerCase())){onToast('This keyword already exists.');return}if(save({keywords:profile.keywords.map(x=>x.id===k.id?{...x,text}:x)}))setEditingKeyword(null)}}><input aria-label="Edit keyword text" value={keywordDraft} onChange={e=>setKeywordDraft(e.target.value)} required/><button className="bp-icon" aria-label="Save keyword"><Check size={16}/></button><button type="button" className="bp-icon" aria-label="Cancel keyword edit" onClick={()=>setEditingKeyword(null)}><X size={16}/></button></form>:<span>{k.text}</span>}<button className="bp-icon" aria-label={'Edit keyword '+k.text} onClick={()=>{setEditingKeyword(k.id);setKeywordDraft(k.text)}}><Pencil size={15}/></button><select aria-label={'Priority for '+k.text} value={k.priority} onChange={e=>save({keywords:profile.keywords.map(x=>x.id===k.id?{...x,priority:e.target.value}:x)})}><option>Must Have</option><option>Nice to Have</option></select><button className="bp-icon" aria-label={'Remove keyword '+k.text} onClick={()=>save({keywords:profile.keywords.filter(x=>x.id!==k.id)})}><X size={16}/></button></div>)}</div>{!shownKeywords.length&&<p className="bp-empty">No keywords match. Try another phrase or add one above.</p>}<p className="bp-muted bp-space">{profile.keywords.length} keywords · {profile.keywords.filter(k=>k.priority==='Must Have').length} must have · {profile.keywords.filter(k=>k.priority==='Nice to Have').length} nice to have</p>
  </Panel>}
  {active===2&&<>
   <Panel title="Your competitive edge" description="The reasons teams choose LunchLink."><div className="bp-advantages">{profile.advantages.map((text,i)=><div key={text}><span className={'bp-check tone-'+i%3}><Check size={18}/></span><p>{text}</p></div>)}</div></Panel>
   <Panel title="Competitors" description="The businesses your audience compares."><form className="bp-add" onSubmit={e=>{e.preventDefault();const url=newCompetitor.trim();const name=competitorName.trim();if(!name)return;try{if(!['http:','https:'].includes(new URL(url).protocol))throw new Error()}catch{onToast('Enter a website URL starting with https:// or http://.');return}if(profile.competitors.some(v=>v.url===url)){onToast('This competitor is already listed.');return}if(save({competitors:[...profile.competitors,{name,url}]})){setNewCompetitor('');setCompetitorName('')}}}><label>Competitor name<input required placeholder="Business name" value={competitorName} onChange={e=>setCompetitorName(e.target.value)}/></label><label>Website URL<input type="url" required placeholder="https://example.com" value={newCompetitor} onChange={e=>setNewCompetitor(e.target.value)}/></label><Button primary><Plus size={16}/>Add competitor</Button></form>{profile.competitors.map(({name,url},i)=><div className="bp-list-row" key={url}><span className={'bp-check tone-'+i%3}><Globe2 size={18}/></span><div><strong>{name}</strong><a href={url} target="_blank" rel="noreferrer">{url}<ArrowUpRight size={14}/></a></div><button className="bp-icon" aria-label={'Remove competitor '+name} onClick={()=>save({competitors:profile.competitors.filter(v=>v.url!==url)})}><Trash2 size={16}/></button></div>)}{!profile.competitors.length&&<p className="bp-muted">No competitors added. Add a website above to start your comparison list.</p>}</Panel>
  </>}
  {active===3&&<>
   <EditPanel title="Content & tone" description="Give every article a familiar voice." profile={profile} onSave={save} fields={[{key:'audience',label:'Target audience',multiline:true,rows:7,maxLength:1200},{key:'tone',label:'Content tone'},{key:'contentTypes',label:'Preferred content types'}]}><h4>Target audience</h4><p className="bp-prose">{profile.audience}</p><div className="bp-tone"><div><span>Content tone</span><strong>{profile.tone}</strong></div><div><span>Preferred formats</span><div className="bp-chips">{profile.contentTypes.split(',').map(v=><span key={v}>{v.trim()}</span>)}</div></div></div></EditPanel>
   <Panel title="Publishing schedule" description="A steady rhythm for your content."><div className="bp-schedule"><label>Publishing frequency<select value={profile.frequency} onChange={e=>save({frequency:e.target.value})}><option>Daily</option><option>Weekly</option><option>Bi-weekly</option><option>Monthly</option></select></label><div><h4>Publish on days</h4><div className="bp-days">{week.map(d=><button aria-pressed={profile.days.includes(d)} key={d} onClick={()=>save({days:profile.days.includes(d)?profile.days.filter(v=>v!==d):[...profile.days,d]})}>{d}<Check size={15}/></button>)}</div></div></div><p className="bp-muted bp-space">Preview preferences only. This does not schedule or publish content.</p></Panel>
   <EditPanel title="Example blog URLs" description="Up to 5 articles from your website to guide your writing style." profile={profile} onSave={patch=>{const urls=patch.examples.split('\n').map(s=>s.trim()).filter(Boolean);if(urls.length>5||urls.some(v=>{try{return !['http:','https:'].includes(new URL(v).protocol)}catch{return true}})){onToast('Enter up to 5 valid website URLs, one per line.');return false}return save({...patch,examples:urls.join('\n')})}} fields={[{key:'examples',label:'Example URLs, one per line',multiline:true}]}>{profile.examples?<ul className="bp-url-list">{profile.examples.split('\n').map(url=><li key={url}><a href={url} target="_blank" rel="noreferrer">{url}<ArrowUpRight size={15}/></a></li>)}</ul>:<p className="bp-muted">No example URLs added yet.</p>}</EditPanel>
   <Panel title="Content locale" description="Spelling, terminology, and cultural context for your writing."><form className="bp-add" onSubmit={e=>{e.preventDefault();save({locale})}}><label>Default locale<select value={locale} onChange={e=>setLocale(e.target.value)}>{Object.entries(locales).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><Button primary>Save locale</Button></form></Panel>
   <Panel title="Blog images" description="A small library of images for your content." action={uploader('images','Upload image')}><div className="bp-image-list">{profile.images.map((item,i)=><figure key={i}><img src={item.data} alt={item.name}/><figcaption>{item.name}<button className="bp-icon" aria-label={'Remove image '+item.name} onClick={()=>save({images:profile.images.filter((_,n)=>n!==i)})}><Trash2 size={16}/></button></figcaption></figure>)}{!profile.images.length&&<div className="bp-empty-image"><Image size={28}/><p>Upload a blog image to preview it here.</p><span>The source’s “Body” image is not imported.</span></div>}</div><div className="bp-foot"><span>Images up to 8 MB · optimized as still previews for browser storage</span><SourceLink>Extract from sitemap in Uplift</SourceLink></div></Panel>
  </>}
  {active===4&&<>
   <EditPanel title="Author details" description="Put a person behind your content." profile={profile} onSave={save} fields={[{key:'authorName',label:'Author name',required:true},{key:'jobTitle',label:'Job title'},{key:'bio',label:'Bio',multiline:true,maxLength:2000},{key:'expertise',label:'Expertise'},{key:'linkedin',label:'LinkedIn URL',type:'url'},{key:'twitter',label:'Twitter / X URL',type:'url'},{key:'facebook',label:'Facebook URL',type:'url'},{key:'authorWebsite',label:'Author website',type:'url'}]}><div className="bp-author"><div className="bp-author-image">{profile.authorImage?<img src={profile.authorImage} alt={profile.authorName||'Author'}/>:<UserRound size={40}/>}</div><div><h3>{profile.authorName||'Your author, introduced.'}</h3><p>{profile.jobTitle||'Add a name, role, and experience to your articles.'}</p>{uploader('authorImage',profile.authorImage?'Replace headshot':'Upload headshot')}<p>JPEG, PNG or WebP · 256 × 256 minimum · up to 1 MB</p></div></div><Details entries={[["Author name",profile.authorName],["Job title",profile.jobTitle],["Expertise",profile.expertise],["LinkedIn",profile.linkedin],["Twitter / X",profile.twitter],["Facebook",profile.facebook],["Website",profile.authorWebsite]]}/><h4>Bio</h4><p className="bp-prose">{profile.bio||'No author bio has been added yet.'}</p></EditPanel>
   <Panel title="Byline preview" description="How your author details come together."><div className="bp-byline"><FileText size={24}/><div><strong>Dietary restriction catering guide</strong><p>{profile.authorName?`By ${profile.authorName}${profile.jobTitle?' · '+profile.jobTitle:''}`:'Add author details to preview the byline.'}</p></div></div></Panel>
  </>}
  {active===5&&<>
   <Panel title="Where you stand in search" description="Ranking snapshot from the original business profile."><div className="bp-rank-heading"><div><span>Average position</span><strong>58<small>/ 100</small></strong></div><div><span>Search visibility</span><strong>0<small>%</small></strong></div></div><div className="bp-rank-track" role="img" aria-label="Average search position 58 on a scale from 1 to 100"><div className="bp-rank-marker">58</div>{Array.from({length:50},(_,i)=><i key={i} className={i<5?'leading':''}/>)}</div><div className="bp-rank-scale"><span>1 · first position</span><span>50</span><span>100</span></div><div className="bp-ranked-keyword"><Search size={21}/><div><span>Top ranking keyword</span><strong>corporate catering Toronto</strong></div><b>#58</b></div><p className="bp-muted">Historical source data, not a live ranking check.</p></Panel>
   <Panel title="The context behind your content"><div className="bp-analysis-links">{[[1,'29','SEO keywords','Phrases shaping your search strategy'],[2,'5','Competitors tracked','The alternatives your audience considers'],[2,'9','Competitive advantages','What sets your business apart']].map(([tab,value,label,desc])=><button key={label} onClick={()=>setActive(tab)}><strong>{value}</strong><span>{label}<small>{desc}</small></span><ArrowUpRight size={20}/></button>)}</div><p className="bp-muted">Counts reflect the source profile snapshot.</p></Panel>
  </>}
  </div></div><footer className="bp-page-footer"><span>LunchLink business context</span><span>Local preview · edits stay in this browser</span></footer>
 </section>
}
