import React,{useRef,useEffect,useState} from 'react';
import {X,ArrowUpRight} from 'lucide-react';
import {reportMetrics} from './ai-insights-data';
import {citationDomains} from './prompt-report';
import {BrandLogo} from './BrandLogo';
import {promptTrend} from './prompt-keywords';
export function PromptDetail({prompt,metrics,business,domainFor,onClose,onRun,busy,canRun}){
 const ref=useRef(null);useEffect(()=>{ref.current.showModal();},[]);
 const [engine,setEngine]=useState('All engines'),[metric,setMetric]=useState('visibility');
 const originalHistory=metrics.history,history=originalHistory.filter(a=>engine==='All engines'||a.engine===engine);
 metrics={...metrics,...reportMetrics(history,business.name).find(b=>b.own),history};
 const brands=reportMetrics(history,business.name),sources=citationDomains(history),trend=promptTrend(history,business.name,reportMetrics), engines=[...new Set(originalHistory.map(a=>a.engine))];
 const assessedRecommendations=history.filter(a=>a.brandAssessment&&a.type!=='Branded'),recommended=assessedRecommendations.filter(a=>a.recommended===true).length;
 const points=trend.filter(p=>p[metric]!=null),max=metric==='position'?Math.max(1,...points.map(p=>p.position)):100;
 const x=i=>trend.length===1?350:45+i*610/(trend.length-1),y=n=>150-n/max*125;
 const label={visibility:'Visibility',sentiment:'Sentiment',position:'Average position'}[metric];
 const value=(n,suffix='')=>n==null?'—':`${n.toFixed(1)}${suffix}`;
 return <dialog ref={ref} className="pr-detail" onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}} aria-labelledby="pr-detail-title"><div>
 <header><span>Prompts / Details</span><button className="cs-button" onClick={onClose} aria-label="Close prompt details"><X size={18}/></button></header>
 <h2 id="pr-detail-title">{prompt.text}</h2><div className="pr-detail-meta"><span className="ai-tag">{prompt.topic}</span><span>{prompt.type}</span><span>{prompt.groupPrompts?'Topic analysis':prompt.tracking?'Active · on demand':'Proposed'}</span></div>
 <label className="pr-detail-engine">AI engine<select value={engine} onChange={e=>setEngine(e.target.value)}><option>All engines</option>{engines.map(e=><option key={e}>{e}</option>)}</select></label>
 <div className="pr-detail-score">{[['Visibility',value(metrics.visibility,'%')],['Recommended',assessedRecommendations.length?`${recommended}/${assessedRecommendations.length}`:'—'],['Average position',metrics.position==null?'—':`#${value(metrics.position)}`],['Sentiment',value(metrics.sentiment)],['Answers',metrics.history.length]].map(([label,n])=><div key={label}><span>{label}</span><strong>{n}</strong></div>)}</div>
 <p className="pr-caption">Metrics use the selected date range. Missing or unassessed values remain empty.</p>
 <section className="pr-trend"><div className="pr-section-head"><h3>Performance over time</h3><select aria-label="Trend metric" value={metric} onChange={e=>setMetric(e.target.value)}><option value="visibility">Visibility</option><option value="sentiment">Sentiment</option><option value="position">Average position</option></select></div>{points.length?<><svg viewBox="0 0 700 190" role="img" aria-label={`${label} by collection date. ${points.length} measured days.`}>{[0,max/2,max].map(n=><g key={n}><line x1="45" x2="655" y1={y(n)} y2={y(n)} className="pr-trend-grid"/><text x="3" y={y(n)+4}>{Math.round(n)}{metric==='visibility'?'%':''}</text></g>)}{trend.map((p,i)=>p[metric]==null?null:<g key={p.date}>{i>0&&trend[i-1][metric]!=null&&<line className="pr-trend-line" x1={x(i-1)} y1={y(trend[i-1][metric])} x2={x(i)} y2={y(p[metric])}/>}<circle className="pr-trend-dot" cx={x(i)} cy={y(p[metric])} r="5"><title>{p.date}: {value(p[metric],metric==='visibility'?'%':'')} · {p.count} answers</title></circle>{(i===0||i===trend.length-1)&&<text textAnchor="middle" x={x(i)} y="180">{p.date}</text>}</g>)}</svg><p className="pr-caption">{points.length===1?'One measured day. Collect on another day to build a trend.':'Only collected dates are shown; gaps are not estimated.'}{metric==='position'?' Lower position is better.':''}</p><details><summary>View trend data</summary><div className="ai-table-scroll"><table><thead><tr><th>Date (UTC)</th><th>Visibility</th><th>Sentiment</th><th>Average position</th><th>Answers</th></tr></thead><tbody>{trend.map(p=><tr key={p.date}><td>{p.date}</td><td>{value(p.visibility,'%')}</td><td>{value(p.sentiment)}</td><td>{value(p.position)}</td><td>{p.count}</td></tr>)}</tbody></table></div></details></>:<p className="pr-caption">No measured {label.toLowerCase()} for this selection.</p>}</section>
 <section><h3>Brand rankings</h3><p className="pr-caption">Who appears in answers to this question</p><div className="ai-table-scroll"><table><thead><tr><th>Brand</th><th>Visibility</th><th>Share of voice</th><th>Sentiment</th><th>Avg position</th></tr></thead><tbody>{brands.map(b=><tr key={b.name}><td><span className="pr-brand"><BrandLogo name={b.name} domain={domainFor(b.name)}/>{b.name}{b.own&&<small>You</small>}</span></td><td><div className="pr-meter"><span>{value(b.visibility,'%')}</span><progress max="100" value={b.visibility||0}/></div></td><td>{value(b.sov,'%')}</td><td>{value(b.sentiment)}</td><td>{b.position==null?'—':`#${value(b.position)}`}</td></tr>)}</tbody></table></div></section>
 <section><h3>Citation sources</h3><p className="pr-caption">Share of collected answers citing each domain</p>{sources.length?<div className="pr-sources">{sources.map(s=><a key={s.domain} href={`https://${s.domain}`} target="_blank" rel="noreferrer"><BrandLogo name={s.domain} domain={s.domain}/><span>{s.domain}<small>{s.domain===business.domain?'Your website':'Third-party source'}</small></span><strong>{Math.round(s.percent)}%</strong><ArrowUpRight size={14}/></a>)}</div>:<p className="pr-caption">No cited sources collected for this question yet.</p>}</section>
 <section><div className="pr-section-head"><h3>Response history <small>{metrics.history.length}</small></h3><button className="cs-button filled" disabled={busy||!canRun} onClick={()=>onRun(prompt)}>{busy?'Collecting…':'Collect / refresh answer'}</button></div>{metrics.history.length?metrics.history.map(a=><details key={`${a.id}-${a.at}`} className="pr-response"><summary><strong>{a.engine}</strong><span>{a.mentioned?'Brand mentioned':'Not mentioned'}</span><time>{new Date(a.at).toLocaleString()}</time></summary><p className="pr-caption">{a.sentiment} · {a.position?`Rank #${a.position}`:'No explicit rank'} · {a.cited?'Your website cited':'Your website not cited'}</p><p className="pr-caption">{a.method}{a.model?` · ${a.model}`:''}</p><p className="pr-answer">{a.answer}</p>{a.searchSuggestions&&<iframe title="Google Search suggestions" sandbox="allow-popups" referrerPolicy="no-referrer" srcDoc={a.searchSuggestions} style={{width:'100%',border:0,minHeight:110}}/>}{a.citations?.length>0&&<details><summary>Source evidence</summary>{a.citations.map((c,i)=><blockquote key={i}>{c.excerpt&&<p>{c.excerpt}</p>}<a href={c.url} target="_blank" rel="noreferrer">{c.title||c.url}</a></blockquote>)}</details>}<ul>{(a.sources||[]).map(url=><li key={url}><a href={url} target="_blank" rel="noreferrer">{url}</a></li>)}</ul></details>):<div className="pr-empty">Collect an answer to see the original response, mentions and citations.</div>}</section>
 </div></dialog>;
}
