import React, { useState } from "react";
import { Link2, Globe2, Plus, TrendingUp, Sparkles, FileText, Clock3, Check, Search, ArrowUpRight } from "lucide-react";
import { Stat } from "./ContentSections";
import "./seo-discovery.css";

const links = [
  ["Workplace Weekly", "Office catering trends for growing teams", "Dietary restriction catering guide", 78, "Editorial", "New", "18 Sep"],
  ["The People Desk", "A better employee lunch experience", "Recurring office meal programs", 72, "Editorial", "Active", "16 Sep"],
  ["Green Table Journal", "Sustainable catering ideas for your office", "Vegan office catering options", 65, "Editorial", "New", "15 Sep"],
  ["Local Business Guide", "Corporate catering partners", "LunchLink homepage", 61, "Directory", "Active", "12 Sep"],
  ["Events & Teams", "Your next team event, sorted", "A corporate catering checklist", 69, "Editorial", "Active", "10 Sep"],
  ["Office Essentials", "Planning inclusive team lunches", "Halal menu compliance", 54, "Directory", "Lost", "08 Sep"],
];
const ideas = [
  {id:1,source:"Reddit",title:"How do you cater for a team with different dietary needs?",context:"A sample office-manager discussion about allergies, vegan options, and inclusive menus.",action:"Share a practical dietary checklist and offer a helpful starting point.",topic:"Dietary requirements",score:96,status:"To do",time:"2 hours ago"},
  {id:2,source:"Open web",title:"A guide to making recurring office lunches easier",context:"An illustrative editorial opportunity covering meal planning for growing teams.",action:"Contribute a simple weekly planning template and a short expert perspective.",topic:"Office meal planning",score:92,status:"In progress",time:"5 hours ago"},
  {id:3,source:"Trustpilot",title:"What customers value in corporate catering",context:"A sample review theme highlighting clear allergen labels and reliable delivery windows.",action:"Use these themes to improve your catering FAQ and delivery information.",topic:"Customer experience",score:89,status:"To do",time:"Yesterday"},
  {id:4,source:"Reddit",title:"Ideas for a more sustainable team lunch",context:"A sample community conversation about reducing packaging and food waste at work.",action:"Offer three low-waste catering ideas with a useful portion-planning tip.",topic:"Sustainable catering",score:87,status:"To do",time:"Yesterday"},
  {id:5,source:"Open web",title:"The inclusive corporate event checklist",context:"An illustrative resource roundup for people planning their next company event.",action:"Prepare a concise checklist covering halal, vegan, and allergen-friendly menus.",topic:"Event planning",score:94,status:"Completed",time:"2 days ago"},
  {id:6,source:"Trustpilot",title:"Make menu choices easier to understand",context:"A sample review theme about menu variety and confidence when ordering for a group.",action:"Create a menu comparison guide with clear portions and dietary labels.",topic:"Menu clarity",score:85,status:"In progress",time:"2 days ago"},
];
function Stats({rows}) { return <div className="cs-stats">{rows.map(([label,value,description,icon],i)=><Stat key={label} label={label} value={value} description={description} icon={icon} color={["purple","green","gold","blue"][i]} values={[[3,4,5,4,7,8],[3,5,4,6,5,7],[2,4,3,6,4,5],[5,3,4,2,3,2]][i]}/>)}</div>; }
function Tag({children}) { return <span className={`sd-tag sd-${children.toLowerCase().replaceAll(" ","-")}`}>{children}</span>; }
function Filters({options,value,onChange}) { return <div className="seo-filters" role="group" aria-label="Filter sample data">{options.map(o=><button key={o} aria-pressed={value===o} onClick={()=>onChange(o)}>{o}</button>)}</div>; }
function SampleNote() { return <p className="sd-sample-note">Sample data for this preview · Sources, activity, and scores are illustrative, not live monitoring.</p>; }

export function BacklinkPreview() {
  const [filter,setFilter]=useState("All links"),[search,setSearch]=useState("");
  const shown=links.filter(l=>(filter==="All links"||l[5]===filter)&&l.join(" ").toLowerCase().includes(search.toLowerCase()));
  return <><div className="cs-page-intro"><div><h2>A stronger network around your content.</h2><p>Explore referring pages, follow link growth, and see what’s new.</p></div><Tag>Sample report</Tag></div>
    <Stats rows={[["Total backlinks",248,"Across your content library",Link2],["Referring domains",86,"Unique sources in this sample",Globe2],["New links",24,"Added this month · sample",Plus],["Lost links",4,"Worth a closer look",TrendingUp]]}/>
    <div className="sd-overview"><section className="panel seo-card"><div className="seo-card-heading"><h3>Backlink growth</h3><span className="seo-muted">Apr – Sep 2026</span></div><div className="sd-growth" role="img" aria-label="Sample backlink totals: April 124, May 148, June 172, July 190, August 228, September 248">{[["Apr",124],["May",148],["Jun",172],["Jul",190],["Aug",228],["Sep",248]].map(([month,value])=><div key={month}><span>{value}</span><div className="sd-bar-track"><i style={{height:`${value/248*100}%`}}/></div><small>{month}</small></div>)}</div><div className="sd-chart-caption"><span className="sd-dot"/>Total backlinks<span>+20 net links in September</span></div></section>
    <section className="panel seo-card"><div className="seo-card-heading"><h3>Your link profile</h3><Link2 size={19}/></div><div className="sd-profile-total"><strong>86</strong><span>domains linking to you</span></div><div className="sd-stack" aria-label="Editorial 62%, directories 25%, communities 13%"><i style={{width:"62%"}}/><i style={{width:"25%"}}/><i style={{width:"13%"}}/></div>{[["Editorial mentions","62%"],["Business directories","25%"],["Community resources","13%"]].map(([label,value],i)=><div className={`sd-breakdown sd-tone-${i}`} key={label}><span><i/>{label}</span><strong>{value}</strong></div>)}<div className="sd-insight"><Sparkles size={17}/><p>Editorial mentions make up most of this sample profile. Keep creating useful, shareable resources.</p></div></section></div>
    <section className="panel seo-report"><div className="seo-card-heading"><h3>Referring pages</h3><span className="seo-muted">6 sample records</span></div><div className="sd-table-tools"><Filters options={["All links","New","Active","Lost"]} value={filter} onChange={setFilter}/><label className="seo-search"><Search size={17}/><input aria-label="Search backlinks" placeholder="Find a source or page…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="seo-table-scroll" tabIndex={0} aria-label="Backlink sample records"><table className="seo-table"><thead><tr>{["Referring page","Links to","Authority","Type","Status","Last seen"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{shown.map(([source,title,target,score,type,status,date])=><tr key={source}><td><div className="sd-source-title"><span className="seo-file-icon"><Globe2 size={18}/></span><div><strong>{source}</strong><small>{title}</small></div></div></td><td>{target}</td><td><span className="seo-score">{score}<small>/100</small></span></td><td className="seo-muted">{type}</td><td><Tag>{status}</Tag></td><td>{date}</td></tr>)}</tbody></table></div>{!shown.length&&<div className="sd-no-results">No matching backlinks. Try another source or status.</div>}<div className="seo-table-footer">Showing {shown.length} of 6 sample referring pages<span>Authority scores are illustrative</span></div></section><SampleNote/>
  </>;
}

export function OpportunityPreview({onToast}) {
  const [rows,setRows]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem("d2-opportunity-statuses")||"{}");return ideas.map(i=>({...i,status:["To do","In progress","Completed"].includes(saved[i.id])?saved[i.id]:i.status}));}catch{return ideas;}});
  const [filter,setFilter]=useState("All sources"),[query,setQuery]=useState(""),[status,setStatus]=useState("All statuses");
  const count=s=>rows.filter(r=>r.status===s).length;
  function update(id,value){const next=rows.map(r=>r.id===id?{...r,status:value}:r);setRows(next);try{localStorage.setItem("d2-opportunity-statuses",JSON.stringify(Object.fromEntries(next.map(r=>[r.id,r.status]))));onToast("Opportunity status saved on this device.");}catch{onToast("Status updated for this session.");}}
  const visible=rows.filter(r=>(filter==="All sources"||r.source===filter)&&(status==="All statuses"||r.status===status)&&`${r.title} ${r.topic}`.toLowerCase().includes(query.toLowerCase()));
  return <><div className="cs-page-intro"><div><h2>Your next good conversation starts here.</h2><p>Find relevant themes, shape a useful response, and keep your next steps moving.</p></div><Tag>Sample opportunities</Tag></div><Stats rows={[["Opportunities",6,"Curated examples for LunchLink",Sparkles],["To do",count("To do"),"Ready for a closer look",FileText],["In progress",count("In progress"),"Ideas taking shape",Clock3],["Completed",count("Completed"),"Reviewed and wrapped up",Check]]}/>
    <div className="sd-opportunity-layout"><div><section className="panel sd-opportunity-toolbar"><Filters options={["All sources","Reddit","Trustpilot","Open web"]} value={filter} onChange={setFilter}/><div className="seo-tools"><label className="seo-search"><Search size={17}/><input aria-label="Search opportunities" placeholder="Find a topic or conversation…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter opportunities by status" value={status} onChange={e=>setStatus(e.target.value)}><option>All statuses</option>{["To do","In progress","Completed"].map(s=><option key={s}>{s}</option>)}</select></div></section><div className="sd-idea-grid">{visible.map(r=><article className="panel sd-idea" key={r.id}><div className="sd-idea-top"><span className="sd-source-chip"><Globe2 size={16}/>{r.source}</span><span className="sd-match">{r.score}% fit</span></div><h3>{r.title}</h3><p>{r.context}</p><span className="sd-topic">{r.topic}</span><div className="sd-next-step"><Sparkles size={16}/><div><strong>Suggested next step</strong><p>{r.action}</p></div></div><div className="sd-idea-bottom"><span>{r.time} · sample</span><select aria-label={`Status for ${r.title}`} value={r.status} onChange={e=>update(r.id,e.target.value)}>{["To do","In progress","Completed"].map(s=><option key={s}>{s}</option>)}</select></div></article>)}</div>{!visible.length&&<div className="panel sd-no-results">No matching opportunities. Try another topic or filter.</div>}</div>
    <aside className="panel seo-card sd-opportunity-aside"><div className="seo-card-heading"><h3>Opportunity mix</h3><Sparkles size={19}/></div><div className="sd-profile-total"><strong>6</strong><span>ideas worth exploring</span></div><div className="sd-stack"><i style={{width:"33.33%"}}/><i style={{width:"33.33%"}}/><i style={{width:"33.34%"}}/></div>{["Reddit","Trustpilot","Open web"].map((s,i)=><button className={`sd-breakdown sd-tone-${i}`} key={s} onClick={()=>setFilter(s)}><span><i/>{s}</span><strong>2 <ArrowUpRight size={13}/></strong></button>)}<div className="sd-aside-divider"/><h3>Your workflow</h3>{["To do","In progress","Completed"].map(s=><button className="sd-breakdown" key={s} onClick={()=>setStatus(s)}><span>{s}</span><strong>{count(s)} <ArrowUpRight size={13}/></strong></button>)}<div className="sd-insight"><Sparkles size={18}/><p>Lead with something useful. A clear answer or practical checklist can be more helpful than a pitch.</p></div><p className="seo-muted sd-aside-note">These are fictional examples. Status changes stay on this device; no replies are sent.</p></aside></div><SampleNote/></>;
}
