import React, { useRef, useState } from "react";
import { Instagram, Facebook, Linkedin, MessageCircle, Check, Minus, Copy, Plus, ArrowUpRight, ShieldCheck, Unplug, CalendarDays } from "lucide-react";
import { CalendarPage } from "./ContentSections";
import "./social-workspace.css";
const platforms=['Instagram','Facebook','LinkedIn','X'];
const icons=[Instagram,Facebook,Linkedin,MessageCircle];
const initialTopics=['Build your first AI visibility baseline','Five checks before you publish an article','A better way to plan your next content batch','One idea, ready for every feed','Turn search questions into useful content','Why your Google Business Profile needs attention'];
const tabs=['Social Posts','Social Calendar','Connections','Settings'];
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback;}catch{return fallback;}}
function caption(title,p){return p==='X'?`${title}. Turn research into useful content, keep your publishing consistent, and understand how your brand appears in AI search. Explore Uplift AI at upliftai.co.`:`${title}\n\nBetter visibility starts with useful content and a consistent process. Bring your keyword research, content planning, publishing, and AI visibility into one workspace with Uplift AI.\n\nStart with one question your audience is asking. Build a clear answer. Review it. Publish it. Learn from the results.\n\nExplore upliftai.co${p==='Instagram'?'\n\n#UpliftAI #SEO #AIVisibility #ContentStrategy':''}`;}
export function SocialWorkspace({library,items,onOpen,onCreate,onToast}){
 const [tab,setTab]=useState(0),[mode,setMode]=useState('Channel readiness'),[selected,setSelected]=useState(0),[platform,setPlatform]=useState('LinkedIn'),[connection,setConnection]=useState(null),[adding,setAdding]=useState(false),[topic,setTopic]=useState('');
 const [topics,setTopics]=useState(()=>{const saved=read('d2-social-topics',initialTopics);return Array.isArray(saved)&&saved.every(t=>typeof t==='string')?saved:initialTopics;});
 const [prefs,setPrefs]=useState(()=>({...Object.fromEntries(platforms.map(p=>[p,true])),review:true,timezone:'Asia/Kolkata',...read('d2-social-preferences',{})}));
 const refs=useRef([]);
 function save(key,value){try{localStorage.setItem(key,JSON.stringify(value));onToast('Saved on this device. No live accounts were changed.');}catch{onToast('Updated for this session; device storage is unavailable.');}}
 const social=items.filter(i=>i.type==='Social post');
 return <section className="social-workspace"><div className="sw-tabs" role="tablist" aria-label="Social media sections">{tabs.map((t,i)=><button key={t} id={`sw-tab-${i}`} ref={el=>refs.current[i]=el} role="tab" aria-controls="sw-panel" aria-selected={tab===i} tabIndex={tab===i?0:-1} onClick={()=>setTab(i)} onKeyDown={e=>{const n=e.key==='ArrowRight'?(i+1)%4:e.key==='ArrowLeft'?(i+3)%4:e.key==='Home'?0:e.key==='End'?3:null;if(n!==null){e.preventDefault();setTab(n);refs.current[n].focus();}}}>{t}</button>)}</div><div id="sw-panel" role="tabpanel" aria-labelledby={`sw-tab-${tab}`}>
 {tab===0&&<><div className="sw-view-switch" role="group" aria-label="Social post view">{['Channel readiness','Content library'].map(v=><button key={v} aria-pressed={mode===v} onClick={()=>setMode(v)}>{v}</button>)}</div>{mode==='Content library'?library:<div className="cs-page"><div className="cs-page-intro"><div><h2>One idea. A thoughtful version for every feed.</h2><p>Review your coordinated sets, check each channel, and fine-tune the copy.</p></div><button className="cs-button filled" onClick={()=>setAdding(!adding)}><Plus size={16}/>Add social topic</button></div>
 <div className="sw-summary"><span><strong>{topics.length}</strong> topic ideas</span><span><strong>18</strong> sample platform outputs</span><span><strong>4</strong> channels to shape</span><span className="sw-sample">Illustrative Uplift AI content sets</span></div>
 {adding&&<form className="panel sw-add" onSubmit={e=>{e.preventDefault();if(!topic.trim())return;const next=[...topics,topic.trim()];setTopics(next);save('d2-social-topics',next);setSelected(next.length-1);setTopic('');setAdding(false);}}><label>Topic<input required maxLength={150} value={topic} onChange={e=>setTopic(e.target.value)} placeholder="The idea you want to share"/></label><button className="cs-button filled">Add topic</button><button className="cs-button" type="button" onClick={()=>setAdding(false)}>Cancel</button></form>}
 <div className="sw-post-layout"><section className="panel sw-panel"><div className="sw-heading"><h3>Channel readiness</h3><span>6 sample sets + your ideas</span></div><p className="sw-muted">Select an idea to review its platform-specific caption.</p><div className="sw-matrix-scroll" tabIndex={0} aria-label="Channel readiness matrix"><table className="sw-matrix"><thead><tr><th>Content set</th>{platforms.map((p,i)=>{const Icon=icons[i];return <th key={p}><span><Icon size={17}/>{p}</span></th>;})}</tr></thead><tbody>{topics.map((t,i)=><tr key={`${i}-${t}`} className={i===selected?'selected':''}><td><button onClick={()=>setSelected(i)}>{t}<small>{i<6?`Topic plan · ${14+i} Sep 2026`:'Your draft idea'}</small></button></td>{platforms.map((p,j)=>{const ready=i<6&&(j>1||i%2===1);return <td key={p}><button className={`sw-cell ${ready?'ready':''}`} aria-label={`${p}: ${i>=6?'Draft idea':ready?j===3?'Caption ready':'Complete':'Not requested'} for ${t}`} onClick={()=>{setSelected(i);setPlatform(p);}}>{ready?<Check size={16}/>:<Minus size={16}/>}<span>{i>=6?'Draft':ready?j===3?'Caption':'Ready':'—'}</span></button></td>;})}</tr>)}</tbody></table></div><div className="sw-legend"><span><Check size={14}/>Ready for review</span><span><Minus size={14}/>Not requested / draft</span></div></section>
 <section className="panel sw-panel sw-caption"><div className="sw-heading"><h3>Caption preview</h3><span>Sample copy</span></div><div className="sw-platform-picker" role="group" aria-label="Caption platform">{platforms.map((p,i)=>{const Icon=icons[i];return <button key={p} aria-label={p} aria-pressed={platform===p} onClick={()=>setPlatform(p)}><Icon size={18}/></button>;})}</div><div className="sw-caption-title"><span className="sw-avatar">U</span><div><strong>Uplift AI</strong><small>{platform} · Draft preview</small></div></div><p className="sw-caption-copy">{caption(topics[selected]||topics[0],platform)}</p><div className="sw-caption-footer"><span>{caption(topics[selected]||topics[0],platform).length} characters</span><button className="cs-button" onClick={async()=>{try{await navigator.clipboard.writeText(caption(topics[selected]||topics[0],platform));onToast('Caption copied.');}catch{onToast('Clipboard unavailable. Select the caption text to copy it.');}}}><Copy size={14}/>Copy caption</button></div><button className="cs-button filled" onClick={()=>onCreate(undefined,topics[selected])}><Plus size={15}/>Create social draft</button></section></div>
 <section className="panel sw-rhythm"><div><CalendarDays size={23}/><h3>Give every idea room to land.</h3><p>Review your social-only schedule before adding the next post.</p></div><div className="sw-rhythm-track" aria-label={`${social.length} social posts in your workspace`}>{social.map((s,i)=><button key={s.id||i} onClick={()=>onOpen(s)} aria-label={`Open ${s.title}`}><i className={`sw-tick-${i%3}`}/><span>{new Date(s.date).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</span></button>)}</div><button className="cs-button" onClick={()=>setTab(1)}>Open social calendar<ArrowUpRight size={15}/></button></section>
 </div>}</>}
 {tab===1&&<><div className="sw-calendar-note"><CalendarDays size={17}/><span>Social posts only · Uses your existing Dashboard 2 content and calendar</span></div><CalendarPage items={social} onOpen={onOpen} onCreate={date=>onCreate(date)}/></>}
 {tab===2&&<div className="cs-page"><div className="cs-page-intro"><div><h2>Bring your channels into the conversation.</h2><p>Keep the same idea connected to the right audience.</p></div><span className="sw-sample">No live accounts connected</span></div><div className="sw-connection-layout"><section className="panel sw-panel"><h3>Publishing destinations</h3>{platforms.map((p,i)=>{const Icon=icons[i];return <div className="sw-connection-row" key={p}><span className={`sw-platform-icon sw-tone-${i}`}><Icon size={24}/></span><div><h3>{p}</h3><p>{['Visual stories and carousel captions','Community updates and conversations','Useful insights for your professional audience','Short updates and timely ideas'][i]}</p></div><span className="sw-disconnected"><Unplug size={13}/>Not connected</span><button className="cs-button" onClick={()=>setConnection(p)}>Connection details</button></div>;})}</section><aside className="panel sw-panel"><h3>A considered publishing flow</h3><ol className="sw-flow">{[['Connect a channel','Authorize your account in the live Uplift AI workspace.'],['Shape the content','Review the creative and caption for each audience.'],['Approve, then publish','Confirm the destination and schedule before going live.']].map(([title,body])=><li key={title}><h4>{title}</h4><p>{body}</p></li>)}</ol><p className="sw-callout"><ShieldCheck size={20}/>This preview never asks for credentials or publishes to your accounts.</p></aside></div>{connection&&<section className="panel sw-panel sw-connection-detail" aria-label={`${connection} connection details`}><div className="sw-heading"><h3>Connect {connection}</h3><button className="cs-button" onClick={()=>setConnection(null)}>Close details</button></div><p>Connect {connection} in the original Uplift AI application. This design preview does not change your live connections.</p><a className="cs-button filled" href="https://dashboard.upliftai.co/dashboard/social/connections" target="_blank" rel="noopener noreferrer">Open connection setup<ArrowUpRight size={16}/></a></section>}</div>}
 {tab===3&&<div className="cs-page"><div className="cs-page-intro"><div><h2>A publishing rhythm that works for you.</h2><p>Choose the channels and review preferences for your social drafts.</p></div></div><form className="sw-settings-layout" onSubmit={e=>{e.preventDefault();save('d2-social-preferences',prefs);}}><section className="panel sw-panel"><h3>Content preferences</h3><label className="sw-setting"><span><strong>Approval required before publishing</strong><small>Keep a review step before content reaches your channels.</small></span><input type="checkbox" checked={prefs.review} onChange={e=>setPrefs({...prefs,review:e.target.checked})}/></label>{platforms.map((p,i)=>{const Icon=icons[i];return <label className="sw-setting" key={p}><span className="sw-setting-title"><Icon size={20}/><span><strong>Generate {p} content</strong><small>Include {p} in your preferred content outputs.</small></span></span><input type="checkbox" checked={!!prefs[p]} onChange={e=>setPrefs({...prefs,[p]:e.target.checked})}/></label>;})}<label className="sw-setting"><span><strong>Timezone</strong><small>Use a consistent reference for your publishing plan.</small></span><select value={prefs.timezone} onChange={e=>setPrefs({...prefs,timezone:e.target.value})}>{['Asia/Kolkata','UTC','America/New_York','Europe/London'].map(t=><option key={t}>{t}</option>)}</select></label><div className="sw-settings-save"><p>Draft preferences only. Live automation remains unchanged.</p><button className="cs-button filled">Save preferences</button></div></section><aside className="panel sw-panel"><h3>Your publishing recipe</h3><div className="sw-recipe-icons">{platforms.map((p,i)=>{const Icon=icons[i];return <span key={p} className={prefs[p]?'enabled':''} aria-label={`${p} ${prefs[p]?'enabled':'disabled'}`}><Icon size={24}/></span>;})}</div><h4>{platforms.filter(p=>prefs[p]).length} channels selected</h4><p className="sw-muted">{prefs.review?'Every draft gets a review before publishing.':'Approval is disabled in these draft preferences.'}</p><div className="sw-recipe-path"><span>One idea</span><span>Channel drafts</span><span>{prefs.review?'Your review':'Ready to schedule'}</span></div><p className="sw-callout"><ShieldCheck size={20}/>Preferences stay on this device until you configure your live workspace.</p></aside></form></div>}
 </div><footer className="sw-footer">Social workspace · Preview content<span>Changes stay on this device · Nothing is published</span></footer></section>;
}
